### ISSUE TITLE
Consider not suggesting pre-release versions

### ISSUE THREAD

**Issue by lnicola** [serayuzgur/crates#10]
This is a matter of taste, arguably.

![image](https://user-images.githubusercontent.com/308347/42182383-52387fb8-7e3e-11e8-9527-1ab278e3bc78.png)

**Comment by serayuzgur** [comment]
Please check version 0.2.1

**Comment by lnicola** [comment]
Thanks. There's still an issue, thought: https://semver.org/#spec-item-9. I've also seen `-rc`, but in general there could be anything there.

**Comment by serayuzgur** [comment]
So, -rc is a common case and lets handle this also. It will be at 0.2.2

**Comment by lnicola** [comment]
I didn't read the code very carefully, can you just look for a hyphen in the version string?
