### ISSUE TITLE
Accessibility regression

### ISSUE THREAD

**Issue by dcormier** [serayuzgur/crates#100]
**Describe the bug**
The previous version used symbols to indicate status; the current version uses _only_ color. I'm colorblind (as are about 10% of males). This is not useful to me.

**To Reproduce**
1. Open your `Cargo.toml` file containing one or more dependencies.

**Expected behavior**
I expect symbols to make it easy to tell the status of my dependencies.

**Screenshots**
<img width="331" alt="image" src="https://user-images.githubusercontent.com/216265/91760563-90cf7b00-eba1-11ea-9a68-bbcc5761ff6b.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Version: vscode 1.48.2; crates 0.5.3

**Comment by serayuzgur** [comment]
Hi, please feel free to change preferences. It uses a template, so you can enter whatever you want.
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/4561330/91761368-6ac7cc00-ebdd-11ea-86c9-de8f36e4f386.png">

**Comment by dcormier** [comment]
More accessible defaults might be a good idea.

**Comment by serayuzgur** [comment]
Yes, it is always hard to select icons for me :) Please, help me with your suggestions.

**Comment by dcormier** [comment]
A simple choice might be: 👍 for compatible and 👎 for incompatible.

Though, if I'm understanding properly, a crate marked as "incompatible" means that there's a newer semver available? (Sorry, I'm new to rust.) In which case, maybe 🎉 for being on the current version and 📢 for there being a newer version available.

**Comment by jestarray** [comment]
what font do i have to install to get the colors working...I'm on a minimal arch linux installation
![image](https://user-images.githubusercontent.com/34615798/92187959-16586280-ee10-11ea-9455-54dd0c96e726.png)

**Comment by serayuzgur** [comment]
Hi, @jestarray I don't use any colors, they are just emojis. You can select a better colored emoji for your distro and edit templates.

**Comment by ArturKovacs** [comment]
Please consider changing the default emojis to ones that are more accessible. These could for example be ✅ and ❌. You earlier mentioned that it's hard to select icons. Could you elaborate on the constraints these icons need to conform so that a suitable alternative could be found?

I appreciate that the defaults can be changed in the settings but if something would be objectively better for most users than why not use that as the default?

Thanks for your consideration 💙

**Comment by serayuzgur** [comment]
defaults changed , hope these will work 
error : "❗️❗️❗️"
incompatible: "❌ ${version}"
compatible: "✅ ${version}"

**Comment by serayuzgur** [comment]
please check 0.5.4
