### ISSUE TITLE
Incorrectly marking 1.4.0 as incompatible with 1.3

### ISSUE THREAD

**Issue by djc** [serayuzgur/crates#101]
Cargo ignores leading zero components of the version number when considering compatibility. So while 0.1.0 and 0.2.0 are not compatible, 1.3.0 and 1.4.0 are (as are 2.2.0 and 2.5.0). Also as far as I know 0.0.1 and 0.0.2 are also incompatible.

![Screen Shot 2020-09-03 at 09 37 48](https://user-images.githubusercontent.com/158471/92085461-239e2e80-edc9-11ea-879b-02b0ffeb5d01.png)

**Comment by serayuzgur** [comment]
I will prepare a good test case and look for it.

**Comment by serayuzgur** [comment]
@djc I couldn't find any doc about it , are you sure ?

https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility

**Comment by djc** [comment]
What part are you looking for exactly?

"This convention also applies to versions with leading zeros. For example, 0.1.0 and 0.1.2 are compatible, but 0.1.0 and 0.2.0 are not. Similarly, 0.0.1 and 0.0.2 are not compatible."

**Comment by djc** [comment]
(My biggest pain point currently here is that "1.3" and "1.4" are considered incompatible.

**Comment by serayuzgur** [comment]
I will work on it, but for a work around can you use caret '^'? Does it works for you?

**Comment by djc** [comment]
That basically seems to run into #104.

**Comment by serayuzgur** [comment]
so lets fix #104  at the new version , later we can work on this.

**Comment by serayuzgur** [comment]
This seems ok what do you think ? 
<img width="268" alt="Screen Shot 2021-01-05 at 23 53 37" src="https://user-images.githubusercontent.com/4561330/103697656-475cc580-4fb1-11eb-919e-f33ade523c45.png">

**Comment by djc** [comment]
Yes, it looks great!

**Comment by serayuzgur** [comment]
please test 0.5.5

**Comment by djc** [comment]
This is with 0.5.4, still seeing some issues.

![Screen Shot 2021-01-05 at 21 59 31](https://user-images.githubusercontent.com/158471/103698220-4e7bd780-4fa1-11eb-9faa-494e23f44d04.png)

**Comment by serayuzgur** [comment]
I think 0.5.5 will fix these. 0.5.4 was for caret support

**Comment by djc** [comment]
Yup, 0.5.5 is looking glorious.
