### ISSUE TITLE
Not working with proxy server on linux

### ISSUE THREAD

**Issue by mlesin** [serayuzgur/crates#102]
**Describe the bug**
In linux environment, where internet connection is only available through proxy server, extension does nothing, infinitely showing "Crates: Fetching crates.io" in status bar.
Environment variables (http_proxy, https_proxy, socks_proxy) are set correctly and other extensions in vscode requiring internet connection are working correctly.

**To Reproduce**
1. On Linux computer without direct internet access, but with connection to proxy server, install this extension,
2. Open existing cargo.toml

**Expected behavior**
Versions are shown after pressing keys ctrl+space 

**Screenshots**
![image](https://user-images.githubusercontent.com/1648252/92456035-15864e80-f1cb-11ea-8541-ffcda14b0320.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Comment by ThePuzzlemaker** [comment]
I'm having this bug on Linux without a proxy
OS: Arch
Version N/A (Rolling)

**Comment by serayuzgur** [comment]
@mlesin  can you please check #104  is your case related with it ?

**Comment by mlesin** [comment]
Looks like you're right.
This issue seems to be incorrect, so I will close it.
