### ISSUE TITLE
Support semver symbols (^, =, ~)

### ISSUE THREAD

**Issue by dkaste** [serayuzgur/crates#104]
**Is your feature request related to a problem? Please describe.**
If you use any of the semver prefix symbols (`^`, `~`, `=`, `>`, `<`, `>=`), the extension will fail to display anything. The status bar in VS Code perpetually displays `Crates: 👀 Fetching crates.io`.

**Describe the solution you'd like**
Handle semver prefix symbols somehow.

**Comment by ThePuzzlemaker** [comment]
Ah, this may be what is causing #102? I'm having the same issue as it and this (even without a proxy), which indicates a shared background.

**Comment by ChaseElectr** [comment]
Any progress？

**Comment by serayuzgur** [comment]
> Any progress？

Hello, I still haven't finished due to my daily work and family responsibilities. I will complete it in the first free time window.

**Comment by serayuzgur** [comment]
please check 0.5.4
