### ISSUE TITLE
spaces in dependencies section prevent syntax highlighting and icons

### ISSUE THREAD

**Issue by kiba-2020** [serayuzgur/crates#105]
I have this nicely formatted dependencies section in my Cargo.toml:

    [dependencies]
    anyhow       = { version = "1.0 ", default-features = false, features = ["std"     ] }
    chrono       = { version = "0.4 ", default-features = false, features = [          ] }
    flexi_logger = { version = "0.15", default-features = false, features = [          ] }
    log          = { version = "0.4 ", default-features = false, features = [          ] }
    num          = { version = "0.3 ", default-features = false, features = [          ] }
    rand         = { version = "0.7 ", default-features = false, features = ["std"     ] }
    reqwest      = { version = "0.10", default-features = false, features = ["blocking"] }
    serde        = { version = "1.0 ", default-features = false, features = ["derive"  ] }
    serde_json   = { version = "1.0 ", default-features = false, features = [          ] }
    sse-client   = { version = "1.1 ", default-features = false, features = [          ] }
    timer        = { version = "0.2 ", default-features = false, features = [          ] }

As soon as a whitespace appears in the version string, the icons showing the version status stop working. 
The second problem is the missing syntax highlighting in a line if there is whitespace after the version string but before the next comma. This was tested with VsCode 1.49.0 and Crates 0.5.3.

**Comment by serayuzgur** [comment]
fixed , you can check at v0.5.4
