### ISSUE TITLE
Stops working when web-sys is added to dependencies

### ISSUE THREAD

**Issue by oelrich** [serayuzgur/crates#107]
**Describe the bug**
No version information is displayed for the web-sys crate or any other crate if the web-sys crate is present.

**To Reproduce**
1. Create new project or open an existing working one.
2. Add "web-sys" under dependencies.
3. No version information appears.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.5.3

**Additional context**
This is possibly due to it having a humongous feature list and exceeding some size limit? It seems to stick on "Fetching crates.io".

**Comment by serayuzgur** [comment]
Hi are you using useLocalCargoIndex ? If not please enable it and try again

**Comment by oelrich** [comment]
Hi! I toggled the flag and the plugin started working for most of the dependencies in the toml-file. It still won't work on web-sys though. On that I get three red exclamation marks and the following error message:

> web-sys: StatusCodeError: 403 - "{"message":"This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size.","errors":[{"resource":"Blob","field":"data","code":"too_large"}],"documentation_url":"https://docs.github.com/rest/reference/repos#get-repository-content\"}" ( Check Reviews )

**Comment by serayuzgur** [comment]
It seems even if you enable local cargo index, extensions fallback to the GitHub index and this is why you have a problem with it. Can you track your local cargo repo file path and share it with me?

**Comment by oelrich** [comment]
This should be the path?
> C:\Users\johan\.cargo\registry\index\github.com-1ecc6299db9ec823\

And then I looked at the Cargo book and found that:

> CARGO_HOME — Cargo maintains a local cache of the registry index and of git checkouts of crates. By default these are stored under $HOME/.cargo (%USERPROFILE%\.cargo on Windows)

So if CARGO_HOME is set (it's not in my case) it should default to ~/.cargo
