### ISSUE TITLE
Incorrect dependency name hangs extension on "Fetching Crates.io"

### ISSUE THREAD

**Issue by djc** [serayuzgur/crates#108]
**Describe the bug**

I mistyped a dependency name today (with `_` instead of `-`), and when I did so the crates extension emoji disappeared, while the status indicator in the status bar showed "Crates: Fetching crates.io...". Ideally 

**To Reproduce**
1. Edit a `Cargo.toml` to add a syntactically correct line with non-existent crate name (like `dsakdsa = ""`)

**Expected behavior**
It would be nice if this showed a question mark emoji instead of one of the usual variants for that dependency only. At a minimum it would be great to still display the other indicators.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 0.5.3

**Comment by almindor** [comment]
This is even worse, if doesn't work with `crate = "=1.0.0"` for example.

**Comment by serayuzgur** [comment]
I think it is related with #104 Can you please check ?

**Comment by serayuzgur** [comment]
please check 0.5.4

**Comment by djc** [comment]
This is fixed for me in 0.5.5, thanks!
