### ISSUE TITLE
Consider ignoring git dependencies

### ISSUE THREAD

**Issue by lnicola** [serayuzgur/crates#11]
Again, a matter of taste:

![image](https://user-images.githubusercontent.com/308347/42182508-af97ee1e-7e3e-11e8-98b0-f3ecc7e5b706.png)

**Comment by serayuzgur** [comment]
I think it is cool to inform about crates version.  But let people decide 😄

**Comment by serayuzgur** [comment]
Hi @lnicola 
Thanks for the idea but it seem no one is having bad time about this.  I am closing this issue as wont fix.
