### ISSUE TITLE
0.5.3 hangs when trying to fetch crates.io registry

### ISSUE THREAD

**Issue by jrconlin** [serayuzgur/crates#113]
**Describe the bug**
The 0.5.3 extension appears to hang at "Fetching crates.io". I'm not sure if it's related to #108, since all dependencies are valid, and 0.5.2 works as expected. We do have a vendored library (one that uses `{version="0", path ="vendor/..." }`, but not sure if that's an issue.

I'm curious if there's a log feature so I can determine what, exactly, is hanging. (e.g. is it failing to fetch the registry? Is there an error in the returned registry data? etc.)

**To Reproduce**
1. Load extension 0.5.3
2. Extension hangs. 

**Expected behavior**
Registry to be fetched and crates resolved (as per 0.5.2)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10, using remote SSH to Ubuntu 20.04
 - Version crates 0.5.3; VSCode 1.52.1

**Additional context**

**Comment by serayuzgur** [comment]
can you please provide the simplified cargo.toml that causes error

**Comment by jrconlin** [comment]
Sure. The file isn't that large, and can be grabbed from:

https://github.com/mozilla-services/syncstorage-rs/blob/master/Cargo.toml

**Comment by serayuzgur** [comment]
can you check lates version 0.5.5 , is it still the same ?

**Comment by jrconlin** [comment]
woot, 0.5.5 works. Thanks!

I'll look at the diff to see what might have been the cause. Just curious.
