### ISSUE TITLE
Parser fails to parse multi-range versions

### ISSUE THREAD

**Issue by djc** [serayuzgur/crates#117]
I'm guessing your parser doesn't yet support multi-range stuff like this:

![Screen Shot 2021-01-12 at 14 55 16](https://user-images.githubusercontent.com/158471/104323207-326abf80-54e6-11eb-886c-fa3745114e8c.png)

(Wild idea: try to compile steveklabnik's semver crate to WebAssembly and use it directly?)

This happens with 0.5.5.

**Comment by serayuzgur** [comment]
Hi, I think comma does not supposed to be there.
I am using [semver](https://www.npmjs.com/package/semver) lib.

**Comment by serayuzgur** [comment]
Hi, I think comma does not supposed to be there.

**Comment by djc** [comment]
Cargo accepts this just fine, so I'm guessing the Node library follows a slightly different specification.

**Comment by serayuzgur** [comment]
Maybe i can clear commas for better tolerance, it seem easy. Does it work correct without commas?

**Comment by djc** [comment]
Yes, if I remove the comma the extension seems to accept it:

![Screen Shot 2021-02-04 at 09 36 52](https://user-images.githubusercontent.com/158471/106866257-870bef80-66cc-11eb-8d17-5d3afd8fd599.png)

**Comment by djc** [comment]
Thanks for fixing this!
