### ISSUE TITLE
Crate fails to function, complaining commands are not found.

### ISSUE THREAD

**Issue by abrassel** [serayuzgur/crates#119]
**Describe the bug**
Crates appears not to function at all.  After running the "update all" command, the following error is reported: `command 'crates.updateAll' not found`

**To Reproduce**
1. Open Command Palette
2. Run the `crates: [update all` command.

**Expected behavior**
All dependencies to be updated.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20

**Comment by serayuzgur** [comment]
Hi, cannot reproduce this issue can you please give more details or try with a different VSC install?

**Comment by Souravgoswami** [comment]
Just trying to learn Rust. Same issue here with this.

![image](https://user-images.githubusercontent.com/37468605/144896472-2200584b-fdd9-4580-8601-bfb5e7a9d657.png)

![image](https://user-images.githubusercontent.com/37468605/144896511-5fe6bede-e8eb-481e-8f52-6dd019310eab.png)

OS: Arch Linux x86-64

**Comment by eminentengg** [comment]
Crates seem to work on VS Code in Linux. But, in Code-OSS I am getting the same issues as the others reported.

![image](https://user-images.githubusercontent.com/100336043/155465377-6c1f1bc8-7734-4a98-aaa5-53c03cef21e1.png)

**Comment by GlobeProgger** [comment]
Same problem here, solved by installing a toml support extension e.g. https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml
