### ISSUE TITLE
Allow hiding the OK indicator

### ISSUE THREAD

**Issue by lnicola** [serayuzgur/crates#12]
Not sure if it's my cold, but this makes me a little dizzy:

![image](https://user-images.githubusercontent.com/308347/42182561-de26b1c0-7e3e-11e8-9143-0dbfdb2c4707.png)

**Comment by serayuzgur** [comment]
You are right , it can be adjustable from settings

**Comment by serayuzgur** [comment]
Please check version 0.2.1
