### ISSUE TITLE
Error reading local Cargo index

### ISSUE THREAD

**Issue by JakubValtar** [serayuzgur/crates#121]
Hi!

**Describe the bug**
When the "Use Local Cargo Index" option is checked, the extension shows error next to each dependency. This happened after I reinstalled Rust.

I have this in my `~/.gitconfig`:
```
[init]
        defaultBranch = main
```
Is it possible that the new version of cargo uses my default branch name for its index and Crates expect it to be called `master`?

**To Reproduce**
1. Open Cargo.toml
2. All crates have ❗️❗️❗️ icon with this tooltip (this was for `anyhow` dependency):
```
**anyhow: Error: Command failed: git --no-pager --git-dir="/home/user/.cargo/registry/index/github.com-1ecc6299db9ec823/.git" show origin/master:an/yh/anyhow fatal: Invalid object name 'origin/master'. **
```

**Expected behavior**
The extension shows the status of each dependency instead of an error. 

 OS: Ubuntu 18.04 running in WSL2 on Windows 10

**Comment by Mihawka** [comment]
For anyone who has this problem you can downgrade to the 5.5 version which still works

**Comment by serayuzgur** [comment]
I think this can be editable from preferences.

**Comment by serayuzgur** [comment]
fixed. please check 0.5.7

**Comment by Mihawka** [comment]
Personally bug still there

**Comment by Mihawka** [comment]
![image](https://user-images.githubusercontent.com/18295323/110715943-7f2cf700-8206-11eb-83ab-daab3ee84a01.png)

**Comment by serayuzgur** [comment]
can you please set crates.localCargoIndexBranch to origin/main from settings  or origin/HEAD

**Comment by Mihawka** [comment]
origin/HEAD work but not origin/main
