### ISSUE TITLE
semver patch not detected as update?

### ISSUE THREAD

**Issue by zeroflaw** [serayuzgur/crates#123]
**Describe the bug**
I rollback to version 0.5.5 due to this issue.
The semver patch isn't being picked up as an update.

**To Reproduce**
pretty_assertions = { version = "0.7.0" }
won't show the available update for 0.7.1

**Expected behavior**
should show update like it did before

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Version 10.15.7

**Comment by Oliver-Piorun** [comment]
Hi! I had the same issue. You have to set `crates.localCargoIndexBranch` to `origin/HEAD`

Greetings!
