### ISSUE TITLE
Extension does not know about latest versions

### ISSUE THREAD

**Issue by max-frai** [serayuzgur/crates#125]
Hello, a few weeks ago this extension started to show me that some crates use invalid version:

<img width="619" alt="Screenshot 2021-03-29 at 17 04 01" src="https://user-images.githubusercontent.com/24208746/112848457-c47b7080-90b0-11eb-9042-f34a660219d5.png">

But (at this time) there is tokio 1.4 and plugin only knows about this versions:

<img width="216" alt="Screenshot 2021-03-29 at 17 00 29" src="https://user-images.githubusercontent.com/24208746/112847978-461ece80-90b0-11eb-9a35-cffa45a92fee.png">

I already tried to update everything like rustup update.

Latest MacOS, VS Code: 1.54.3

**Comment by serayuzgur** [comment]
can you please share settings, did you checked "crates.listPreReleases"? crates looks versions from cargo registry

**Comment by Elabajaba** [comment]
I have the same issue. Changing `Crates: Local Cargo Index Branch` from `origin/master` to `origin/HEAD` fixed it for me.

**Comment by max-frai** [comment]
@serayuzgur As @Elabajaba said, changing origin/master -> origin/HEAD fixes issue for me
