### ISSUE TITLE
Getting red exclamation marks, help text "command failed...etc"

### ISSUE THREAD

**Issue by raum-dellamorte** [serayuzgur/crates#127]
**Describe the bug**
I quit getting version numbers, only 3 red exclamation marks.  The help text is:
`**image: Error: Command failed: git --no-pager --git-dir="/Users/raum/.cargo/registry/index/github.com-1ecc6299db9ec823/.git" show origin/master:im/ag/image fatal: invalid object name 'origin/master'. ** ( Check Reviews )`
where '`image`' is the crate.  All crates have their own version of this message.

**To Reproduce**
I installed VSCodium. (VSCode minus Microsoft telemetry)
I created a new rust project.
I installed the rust extension, which is set to use rustc and rls from PATH.
I installed this extension and the 'Search crates.io' extension (which is now off, still broken)
It worked for a few minutes.  I pasted the dependencies for wgpu.  I updated a couple of versions, image was one of them.  It wouldn't compile bc I hadn't installed the VulkanSDK.  The exclamations showed up.  I installed the VulkanSDK and the build succeeded, but the red exclamations didn't go away.  Uninstalled/reinstalled extension.  No go.

**Expected behavior**
To see the latest version numbers for crates.

**Screenshots**
<img width="277" alt="image" src="https://user-images.githubusercontent.com/1555004/113244179-f6cbd000-9260-11eb-85a0-fd0459686664.png">

**Desktop (please complete the following information):**
 - OS: macos
 - Version 11.2.3
 - M1 Chip (Arm64)

**Comment by RustyYato** [comment]
I'm also getting this  `v0.5.6^`, `v0.5.5` works fine. It doesn't matter what crate it is, all of them give the triple exclamation mark.

**Comment by serayuzgur** [comment]
please change localCargoIndexBranch setting to origin/HEAD

**Comment by raum-dellamorte** [comment]
I opened the settings of the `crates` extension, found `Crates: Local Cargo Index Branch` and changed it from `origin/master` to `origin/HEAD` and that fixed most of the problem.  I'm still getting an error saying `failed to parse manifest at /path/to/Cargo.toml`, and only when crates is enable, but version tracking is working again.  Thanks, @serayuzgur !  This extension is hard to live without!

**Comment by raum-dellamorte** [comment]
Ah, actually that error was my mistake for not having created `./src/lib.rs` yet :)

**Comment by Alfxjx** [comment]
I ran into this problem by setting the wrong mirror source of crate.io, Maybe the mirror URL should be like `https://<some_url>.git`. 
now I use tuna and it works good

**Comment by felipelalli** [comment]
> I opened the settings of the `crates` extension, found `Crates: Local Cargo Index Branch` and changed it from `origin/master` to `origin/HEAD` and that fixed most of the problem. ~I'm still getting an error saying `failed to parse manifest at /path/to/Cargo.toml`, and only when crates is enabled, but version tracking is working again.~ Thanks, @serayuzgur ! This extension is hard to live without!

This solved for me. But why isn't that the default?
