### ISSUE TITLE
Error fetching crates when using WSL's git executable

### ISSUE THREAD

**Issue by kotx** [serayuzgur/crates#137]
**Describe the bug**
When using [wsl2exe](https://github.com/yuk7/wsl2exe), the extension will fail to fetch crates:

With wsl2_ap:
```
**twilight-model: Error: Command failed: git --no-pager --git-dir="C:\Users\toast\scoop\persist\rustup.cargo\registry\index\github.com-1ecc6299db9ec823.git" show origin/HEAD:tw/il/twilight-model fatal: not a git repository: 'C:\Users\toast\scoop\persist\rustup.cargo\registry\index\github.com-1ecc6299db9ec823.git' ** ( Check Reviews )
```

With wsl2_ap.exe:
```
**twilight-model: Error: Command failed: git --no-pager --git-dir="C:\Users\toast\scoop\persist\rustup.cargo\registry\index\github.com-1ecc6299db9ec823.git" show origin/HEAD:tw/il/twilight-model ERROR: Path translation failed. ** ( Check Reviews )
```

**To Reproduce**
1. Download wsl2exe
2. `copy wsl2exe(_ap).exe C:\.bin`
3. Add `C:\.bin` to path
3. Open `Cargo.toml` in the Crates extension
4. Notice the !!! next to your packages.

**Expected behavior**
The packages are fetched successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/33439542/114483502-4ee9c700-9bbd-11eb-899e-3ae93df7c1d5.png)
![image](https://user-images.githubusercontent.com/33439542/114484740-9a04d980-9bbf-11eb-8429-61d060467e7e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (with WSL2)
 - Version 0.5.7

**Comment by serayuzgur** [comment]
@kotx  can you please check with the new version. Maybe it was because of branches

**Comment by kotx** [comment]
Seems to work now. But if anything else happens I'll reopen. Thanks!

**Comment by Student-operating** [comment]
i have the same question , bug i did not install wsl2exe . do you know how can i fix that ?
