### ISSUE TITLE
Manifest not recognised in subdirectories

### ISSUE THREAD

**Issue by TilBlechschmidt** [serayuzgur/crates#142]
**Describe the bug**
`Cargo.toml` in subdirectories e.g. in a workspace is not recognised.

**To Reproduce**
1. Open a folder in VSCode
2. Create a subfolder and run `cargo init` in it
3. Open the newly created `subfolder/Cargo.toml`
4. See nothing happening

**Expected behavior**
It would be expected that the manifest is parsed regardless of the location, especially since there are no options to specify the locations to search at. In my case, I've got a VSCode monorepo workspace with multiple Rust crates in subfolders and it is not possible to use this extension.

**Screenshots**
<img width="680" alt="image" src="https://user-images.githubusercontent.com/5037967/119811561-8b605080-bee7-11eb-8073-ad1ad186aa29.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Plugin Version 0.5.9

**Comment by TilBlechschmidt** [comment]
For reference, here is the repository from the screenshot: https://github.com/TilBlechschmidt/WebGrid

Oddly enough, it looks like you are parsing just the `fileName` and check if it ends in `Cargo.toml` [here](https://github.com/serayuzgur/crates/blob/c0b97de0bf3419495fa87f1f300b456e95e70c77/src/core/listener.ts#L92). So I'm not quite sure why it isn't working.

**Comment by serayuzgur** [comment]
@TilBlechschmidt, I double checked it and code does not block subfolders only checks file name, I tried 3 different projects both with `open folder` and `open workspace` scenarios and it all works.
<img width="1245" alt="Screen Shot 2021-07-26 at 11 58 23" src="https://user-images.githubusercontent.com/4561330/126963017-2a041545-6f5e-4c49-8f33-8af3f3da5b01.png">

**Comment by Lcchy** [comment]
Hey there, just to chime in and say that I have the exact same problem (and a colleague of mine too).
We're both on Ubuntu 21.04, with the extension on version 0.5.9.
Please let me know what kind of information could be useful to debug this and thanks for the nice project!
