### ISSUE TITLE
Incorrect semantic versioning parsing for beta versions

### ISSUE THREAD

**Issue by msdrigg** [serayuzgur/crates#147]
**Describe the bug**
This crate incorrectly parses semantic versioning for beta versions. For example, it places `1.0.0-beta.2` as more recent than `1.0.0-beta.10`

**To Reproduce**
1. Create a Cargo.toml with the following dependency: `tracing-actix-web = "0.4.0-beta.13"`
2. Open this file in vs-code
3. Make sure to enable "List Pre Releases" in settings for this extension.
4. Notice that the crates extension marks this dependency as out-of-date because there is a "newer" version `0.4.0-beta.9`

**Expected behavior**
I would expect the version `1.0.0-beta.13` to be shown as more recent than `1.0.0-beta.9`

https://semver.org defines how beta versions should be ranked under SemVer Specification 11.4:

> Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/45189381/135310418-6d5801c8-2d27-4586-82b5-36e95692a114.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 0.5.9

**Comment by msdrigg** [comment]
Note, the config has loaded beta.13 version, but it places it below beta.9. See this screenshot:

![image](https://user-images.githubusercontent.com/45189381/135312561-68c95234-db36-45f5-8ec1-af2501800bc8.png)

**Comment by kotx** [comment]
This doesn't seem to respect release candidate versions. 
![image](https://user-images.githubusercontent.com/33439542/139597380-5a4354c5-caf0-4797-ac2b-225d1ec8531b.png)

**Comment by msdrigg** [comment]
Did you check the box for 'List Pre Releases' in the extension settings?

**Comment by kotx** [comment]
> Did you check the box for 'List Pre Releases' in the extension settings?

That worked, thanks! Though, it's sort of strange that pre-release versions show up as an "x".

**Comment by msdrigg** [comment]
Yea I would agree it’s unexpected behavior. Maybe file an issue for it

**Comment by kotx** [comment]
Opened #151
