### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by samuela** [serayuzgur/crates#152]
**Is your feature request related to a problem? Please describe.**
Currently `crates` only runs if it detects a Cargo.toml file in the root directory of the VSCode workspace. However this causes friction in any setup where the Cargo.toml file doesn't happen to be in the root directory.

**Describe the solution you'd like**
The `crates` extension to work on any Cargo.toml file that's opened regardless of whether it's in the root directory of the workspace.

**Describe alternatives you've considered**
Opening separate VSCode windows for every cargo project in my overall project.

**Additional context**
n/a

**Comment by serayuzgur** [comment]
Hi @samuela, i checked it from a sample project and it seems to work with nested folders. Also, listener does not check and folder structure `fileName.toLocaleLowerCase().endsWith("cargo.toml")`, You have to help me to understand your situation.


![Screen Shot 2022-01-04 at 15 26 56](https://user-images.githubusercontent.com/4561330/148058925-70b95954-5ae3-46fd-85cd-baa7d62deb62.png)

**Comment by samuela** [comment]
I'm in a situation where the root directory is not itself a rust project. In that case crates does not activate.

**Comment by serayuzgur** [comment]
Mine is a plain folder, also I deleted the outer `Cargo.toml` but the result is still the same. 
![Screen Shot 2022-01-13 at 11 57 55](https://user-images.githubusercontent.com/4561330/149298329-ab4814bc-d5ae-4556-8ad4-86455f5fee7d.png)

Can you please open the logs before opening `Cargo.toml` and send me the log output. 

You can see the explanation below.
![Screen_Shot_2022-01-13_at_12_01_12](https://user-images.githubusercontent.com/4561330/149299076-2e714b91-e950-4fdb-b807-dc03b46d050b.png)

**Comment by serayuzgur** [comment]
Since no action or response , closing.
