### ISSUE TITLE
Local cargo index is significantly outdated

### ISSUE THREAD

**Issue by LJNeon** [serayuzgur/crates#154]
**Describe the bug**
With the "Use Local Cargo Index" setting enabled, the extension provides seriously outdated crate versions. Disabling that setting resolves the issue, but re-enabling it does solve the issue. Uninstalling and reinstalling the extension also doesn't fix.

**Expected behavior**
If there's a local index enabled by default, it should be kept up-to-date.

**Screenshots**
![image](https://user-images.githubusercontent.com/23249107/149251642-07820108-aeed-48d2-8e75-351e954f7bac.png)
![image](https://user-images.githubusercontent.com/23249107/149251675-886d4fcc-c308-43dd-b462-21985b50f4af.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Version [e.g. 22] 21H1

**Comment by LJNeon** [comment]
If this helps diagnose the issue: I haven't opened VSCode on that computer in months. The local index versions appear to be from around when I last opened VSCode.

**Comment by sardobi** [comment]
I'd been putting up with outdated dependency info for many months - this issue helped me work around it, thanks.

If disabling "Use Local Cargo Index" makes the problem go away, is there any reason not to make it the default?

**Comment by ivan** [comment]
I think my local Cargo index stopped updating because I started using cargo only with `CARGO_UNSTABLE_SPARSE_REGISTRY=true`.

**Comment by novedevo** [comment]
Sparse registry was stabilized in Rust 1.68, and will become the default in 1.70, so this error is likely to occur more and more often. I have sparse registry enabled for the performance benefits, and have been getting a lot of rate limit exceeded messages.

**Comment by jnicholls** [comment]
I worked around this by changing the setting `Local Cargo Index Hash` to point to my `CARGO_UNSTABLE_SPARSE_REGISTRY=true` directory which is named `index.crates.io-<hash>` instead of `github.com-<hash>` used with the legacy git crates.io protocol. Look under the `~/.cargo/registry/cache/` directory for your cache directory name.

**Comment by serayuzgur** [comment]
Since there are many issues going related with this, we have our own index server now.  No more local checks with v0.6.0
