### ISSUE TITLE
Add Extension to Open VSX

### ISSUE THREAD

**Issue by manuth** [serayuzgur/crates#161]
Currently, this extension can only be installed in Visual Studio Code.
However, there are a lot (truly) open source alternatives to VSCode such as VSCodium, OpenVSCode Server etc. which currently aren't able to use this extension.

Could you please publish this extension to [Eclipse's Open VSX](https://open-vsx.org/) in order to be able to use this extension in VSCode's open source altvernatives?

That'd be great 😄

**Comment by filiptronicek** [comment]
At OpenVSX, we have documented the whole process, so it should be pretty straight forward 🙂. You can find the guide at https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md. Please ping me if you need any help with the implementation!

cc @serayuzgur

**Comment by pentamassiv** [comment]
I see that the extension is available on open-vsx, but it says the owner is not verified. I guess the service account "open-vsx" did it and it can be trusted?

**Comment by manuth** [comment]
> I see that the extension is available on open-vsx, but it says the owner is not verified. I guess the service account "open-vsx" did it and it can be trusted?

It sure can be trusted. Extensions published by "open-vsx" are the ones which are being published using the automated scripts in this repository:
https://github.com/open-vsx/publish-extensions

This project is used for publishing popular extensions which haven't been published to open-vsx by their actual author yet.
