### ISSUE TITLE
Git dependency

### ISSUE THREAD

**Issue by Steven11q** [serayuzgur/crates#167]
When I first installed this I did not realize I needed git for it to work, and after installing git it worked.

It might be useful to say somewhere on the page that Git is a needed dependency.

I just think it would be nice for newcomers to know they need git, but git in general is just a useful tool to have so its a bit redundant?

**Comment by serayuzgur** [comment]
Since there are many issues going related with this, we have our own index server now.  No more local checks with v0.6.0
