### ISSUE TITLE
Add support for workspace.dependencies

### ISSUE THREAD

**Issue by Christiaan676** [serayuzgur/crates#168]
**Is your feature request related to a problem? Please describe.**
With the [Rust 1.64 release ](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html) support was added for [workspace dependencies](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table). The plugin will correctly detect the dependencies in the workspace Cargo.toml, but the `<dependencie>.workspace = true` in the projects in the workspace will result in three red exclamation marks.

**Describe the solution you'd like**
Don't show the red exclamation marks in the project dependencies when the dependency exists in the workspace.

**Comment by TheQuantumPhysicist** [comment]
I'm really confused. [A project I'm working on](https://github.com/mintlayer/mintlayer-core/blob/b4a5dcf9bdf7400d3c7cd90616d398ceeb6bdbee/common/Cargo.toml#L24) still shows "!!!" besides all workspace dependencies:

<img width="321" alt="image" src="https://user-images.githubusercontent.com/8694366/221810471-7c8d87bc-7949-483d-8554-54dc29966cf7.png">

Why is this considered solved? Can someone please help me understand why this issue that has been solved 5 months ago still has effect on work today?

**Comment by Christiaan676** [comment]
The fix was merged, but unfortunately no release has been made. 

@serayuzgur Would you consider creating a release to the market place? This would help a lot of people.
