### ISSUE TITLE
Change the way of toml parsing.

### ISSUE THREAD

**Issue by serayuzgur** [serayuzgur/crates#17]
Due to limitations of the toml parser code has lots of regex and performance may be damaged by that.

**Comment by serayuzgur** [comment]
Hi @userzimmermann ,
Since you sent regexp PR's, I think this issues test will be  secure at you hands. Can you help me to close this issue ? If yes, please pull master and test a build from that.

I wrote the parser from stratch. All alternatives were bad or I was unable to make them work. I know it is risky but you know it is only version indexing.

**Comment by zimmermannmobile** [comment]
Nice work, @serayuzgur! Of course I'll help

Which alternatives did you try? I would also like to take a look at them. And we could surely also simplify your parser with some regexps... :)

**Comment by serayuzgur** [comment]
Thanks for the help,I tried the projects listed below.
[BinaryMuse/toml-node](https://github.com/BinaryMuse/toml-node)
[jakwings/toml-j0.4](https://github.com/jakwings/toml-j0.4)
[JonAbrams/tomljs](https://github.com/JonAbrams/tomljs)
[alexbeletsky/toml-js](https://github.com/alexbeletsky/toml-js)
[ldthomas/apg-js](https://github.com/ldthomas/apg-js2)

Yes we can simplify it :) actually it is draft work and open for all kind of development.

**Comment by serayuzgur** [comment]
Hi @zimmermannmobile  
What do you think? Did you find any usable solution?

**Comment by userzimmermann** [comment]
Hi @serayuzgur 

With also accepting `\r` as whitespace in your custom TOML parser (PR #21), the whole extension works fine for me so far in the current state

It's also nice that your re-design implicitly makes same dependencies in multiple `[target...]` tables getting treated separately regarding to version check, which didn't work before. I originally wanted to raise an issue about that, but then had somehow forgot about doing so :D 

I was able to create a JavaScript parser grammar with https://github.com/ldthomas/apg-js2 from https://github.com/toml-lang/toml/blob/master/toml.abnf but didn't figure out so far how to create the complete parser from all the `apg` components. I'm thinking about creating a separate project for a generic TOML parser libraray, which I can then also re-use for a VSCode Python dependencies extension

**Comment by serayuzgur** [comment]
@userzimmermann  Thanks for all of your work. I will megre PR and you name will be at both change log and readme
For apg-js2 good luck :)
