### ISSUE TITLE
Please add support for `cargo add` and `cargo remove` commands

### ISSUE THREAD

**Issue by lucatrv** [serayuzgur/crates#178]
Similarly to the [`cargo fetch`](https://doc.rust-lang.org/cargo/commands/cargo-fetch.html) and [`cargo update`](https://doc.rust-lang.org/cargo/commands/cargo-update.html) commands, which currently can be run from within VS Code, it would be very convenient to add support for [`cargo add`](https://doc.rust-lang.org/cargo/commands/cargo-add.html) and [`cargo remove`](https://doc.rust-lang.org/cargo/commands/cargo-remove.html) commands, respectively to add and remove dependencies.

Note: `cargo add` was introduced with [Rust 1.62](https://blog.rust-lang.org/2022/06/30/Rust-1.62.0.html#cargo-add), and `cargo remove` was introduced just today with [Rust 1.66](https://blog.rust-lang.org/2022/12/15/Rust-1.66.0.html#cargo-remove). These two commands were first implemented in [`cargo edit`](https://github.com/killercup/cargo-edit). In future other commands from [`cargo edit`](https://github.com/killercup/cargo-edit) may be integrated into [Cargo](https://doc.rust-lang.org/cargo/), such as [`cargo upgrade`](https://github.com/killercup/cargo-edit#cargo-upgrade).

**Comment by serayuzgur** [comment]
Since there are many issues going related with this, we have our own index server now.  No more local checks with v0.6.0 .
Do you still need this ?

**Comment by lucatrv** [comment]
I was not aware about issues, I confirm that in my opinion it would be a useful addition (which I thought was pretty trivial to add), but of course I can also live using the terminal.
