### ISSUE TITLE
Always getting error from git on Windows

### ISSUE THREAD

**Issue by amg98** [serayuzgur/crates#184]
**Describe the bug**

After installing the extension, the error shown in the following screenshot appears on all dependencies:

![a](https://user-images.githubusercontent.com/37532652/215324066-477d0d92-07ba-469e-970b-81216148bf42.png)

**To Reproduce**
1. Install extension
2. Go to some project Cargo.toml file
3. Even though crates are downloaded and compiled correctly, the error shows up

**Expected behavior**
I expect showing the correct version number for each dependency

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Git: 2.39.0 (installed using MinGW-W64, git is available in the PATH environment variable)
 - Crates extension version: latest from Marketplace
 - Rust version: 1.65.0 (stable, target is MSVC)

**Comment by JohnScience** [comment]
@amg98 Check the value of `crates.localCargoIndexHash` configuration key. It must be `index.crates.io-6f17d22bba15001f` instead of `github.com-1ecc6299db9ec823`.

**Comment by serayuzgur** [comment]
Since there are many issues going related with this, we have our own index server now.  No more local checks with v0.6.0
