### ISSUE TITLE
Out-of-date information not showing versions released since 20th of June 

### ISSUE THREAD

**Issue by V0ldek** [serayuzgur/crates#194]
**Describe the bug**
The extension has out-of-date version information, not seeing versions released even a week ago. The easiest crate to see this on for me is `itertools`, which showsa 0.10.5 even though 0.11.0 was released on the 20th of June.

**To Reproduce**
1. `cargo new` an app
2. Add `itertools = "0.11.0"` to Cargo.toml
3. Extension claims that the version doesn't exist and display ❌ 0.10.5

**Expected behavior**
The extension does not tell me that my Cargo.toml is invalid even though it is valid.

**Screenshots**
![image](https://github.com/serayuzgur/crates/assets/20441980/87fb285b-06cc-45c9-96aa-926d3b12e86d)

**Desktop (please complete the following information):**
 - OS: both Linux and Windows
 - Version: v0.5.11

**Additional context**
Other crates that exhibit this that I can see:
- `clap` (4.3.5 released on 20th of June, extension shows 4.3.4)
- `memmap2` (0.7.1 released on 24th of June, extension shows 0.7.0)

**Comment by V0ldek** [comment]
I actually cannot repro this on my other machine, so it is very likely that this is not a bug but me being dense. I'd appreciate an explanation anyways.

**Comment by livercat** [comment]
I also see this issue, seems to be caused by the default setting `crates.useLocalCargoIndex=true`. Setting it to false clears this problem, although I would have expected `cargo update` to fix it as well (it does not).

**Comment by Massimiliano-solutiontech** [comment]
Same problem and solved with `crates.useLocalCargoIndex=true` as well

The screenshots shows the issue with the `tauri` crate and `crates.useLocalCargoIndex=false`

![Screenshot 2023-06-28 alle 23 28 38](https://github.com/serayuzgur/crates/assets/75322363/0f81972a-d1c3-4ccd-9ccc-7ee8e6775f40)
![Screenshot 2023-06-28 alle 23 28 50](https://github.com/serayuzgur/crates/assets/75322363/ac33a0e2-e222-4e37-847e-cb8fc0faa2fa)

**Comment by plafue** [comment]
In my case, the directory of the index mentioned in this extension's settings was not being updated anymore.

I checked `~/.cargo/registry/index` and used the name of the up-to-date directory as the value of the `crates.localCargoIndexHash` configuration key. 

![image](https://github.com/serayuzgur/crates/assets/1915763/54d4ec3c-0c28-4c83-b12f-69dae92338d7)

Why did it change? No idea :shrug: . I hope this helps somebody.

**Comment by GeoffClements** [comment]
I fixed this by unticking Crates: Use Local Cargo Index.

**Comment by 0x00A** [comment]
> Why did it change? No idea 🤷 . I hope this helps somebody.

Could this be due to Cargo defaulting to using the sparse protocol instead of git in Rust 1.70.0? https://github.com/rust-lang/cargo/pull/11791/

Anyway, the changing the path from the `github.com-<hash>` to the `index.crates.io-<hash>` seems to fix the issue for me as well.

**Comment by JohnScience** [comment]
@0x00A As far as I understand, the hashes are the same for everyone.

For anyone wondering. Check the value of `crates.localCargoIndexHash` configuration key. It must be `index.crates.io-6f17d22bba15001f` instead of `github.com-1ecc6299db9ec823`.

**Comment by serayuzgur** [comment]
Since there are many issues going related with this, we have our own index server now.  No more local checks with v0.6.0
