### ISSUE TITLE
Failed to find crates version with metadata

### ISSUE THREAD

**Issue by inflation** [serayuzgur/crates#195]
**Describe the bug**
I'm using the metadata part of SemVer to keep tracking of the linked C library version, e.g., `jpegxl-sys` `0.8.2+libjxl-0.8.2`, after a certain version, 0.6.1. Now, the plugin only recognized versions before the change. 

**To Reproduce**
1. Depend on `jpegxl-sys = 0.8.2`
2. The plugin suggests the latest version is `0.6.1`

**Expected behavior**
The plugin should suggests `0.8.2` and show versions after `0.6.1`

**Screenshots**
<img width="202" alt="CleanShot 2023-07-04 at 20 23 54@2x" src="https://github.com/serayuzgur/crates/assets/2375962/3ca22a95-e52a-4e47-94d4-720061d9b43c">
<img width="211" alt="image" src="https://github.com/serayuzgur/crates/assets/2375962/25b72e58-715b-4ae5-8bfb-9c95e09d43cb">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 13.4.1

**Comment by JohnScience** [comment]
@inflation Check the value of `crates.localCargoIndexHash` configuration key. It must be `index.crates.io-6f17d22bba15001f` instead of `github.com-1ecc6299db9ec823`. It's related to usage of sparse protocol.

**Comment by inflation** [comment]
@JohnScience Still happens after the changes, but I found out that enable `crates.listPreReleases` would show those versions.

**Comment by serayuzgur** [comment]
Since there are many issues going related with this, we have our own index server now. No more local checks with v0.6.0. Please check again since prerelase option only filters according to the "-" in the version and nothing to do with name

**Comment by inflation** [comment]
Now I can't even retrieve the versions:
```
Completed with errors
derive_builder: Error: read ECONNRESET
image: Error: read ECONNRESET
thiserror: Error: read ECONNRESET
half: Error: read ECONNRESET
byteorder: Error: read ECONNRESET
jpegxl-sys: Error: read ECONNRESET
image: Error: read ECONNRESET
lcms2: Error: read ECONNRESET
testresult: Error: read ECONNRESET
criterion: Error: read ECONNRESET
```

**Comment by ssrlive** [comment]
Me too @inflation 
```
Completed with errors
as-any: Error: connect ETIMEDOUT 24.199.121.34:443
async-trait: Error: connect ETIMEDOUT 24.199.121.34:443
byteorder: Error: connect ETIMEDOUT 24.199.121.34:443
bytes: Error: connect ETIMEDOUT 24.199.121.34:443
thiserror: Error: connect ETIMEDOUT 24.199.121.34:443
tokio: Error: connect ETIMEDOUT 24.199.121.34:443
clap: Error: connect ETIMEDOUT 24.199.121.34:443
dotenvy: Error: connect ETIMEDOUT 24.199.121.34:443
env_logger: Error: connect ETIMEDOUT 24.199.121.34:443
log: Error: connect ETIMEDOUT 24.199.121.34:443
rand: Error: connect ETIMEDOUT 24.199.121.34:443
tokio: Error: connect ETIMEDOUT 24.199.121.34:443
trust-dns-proto: Error: connect ETIMEDOUT 24.199.121.34:443
```

![image](https://github.com/serayuzgur/crates/assets/30760636/f2f818f5-6fc1-4d6d-8bbc-ab90c0aa3fc1)

**Comment by serayuzgur** [comment]
What is the current status?

**Comment by inflation** [comment]
> What is the current status?

Same as before.

**Comment by serayuzgur** [comment]
> > What is the current status?
> 
> Same as before. The path should be the same so I could at least try to use the official URL or a mirror. But now it's 404 if I manually set the URL.

API is not and will not be same with crates.io, due to some optimizations. 

The question is why you are having this issue and lets focus on this.
please try to access to a sample URL like `https://api.crates-vsc.space/index/versions/weld` from browser. If you fail try with a VPN. If it succeeds it means it is ISP

Can you please share your cargo TOML or, share the dependency count in it ?

**Comment by ssrlive** [comment]
![image](https://github.com/serayuzgur/crates/assets/30760636/15fc5180-6afa-4521-ae8d-4e81ae5ffdeb)

**Comment by inflation** [comment]
<img width="872" alt="image" src="https://github.com/serayuzgur/crates/assets/2375962/a6d24de6-211b-42f1-b633-4a9e67757f3a">
Can't access the server.

**Comment by BarbossHack** [comment]
> API is not and will not be same with crates.io, due to some optimizations.

What are these optimisations ? Just for the Json unnecessary fields ? https://github.com/serayuzgur/crates/issues/197#issuecomment-1637195184

**Comment by serayuzgur** [comment]
> > API is not and will not be same with crates.io, due to some optimizations.
> 
> What are these optimisations ? Just for the Json unnecessary fields ? [#197 (comment)](https://github.com/serayuzgur/crates/issues/197#issuecomment-1637195184)

Caching , slicing, requesting multiple crates at once (in progress)

**Comment by serayuzgur** [comment]
> ![image](https://user-images.githubusercontent.com/30760636/253968323-15fc5180-6afa-4521-ae8d-4e81ae5ffdeb.png)

The browser is functioning properly, indicating that there might be an issue with Vsc's connection. Do you have any specific settings related to it, such as a proxy or other configurations?

**Comment by serayuzgur** [comment]
> Can't access the server. It would be great to have an option to use the official index URL format, which is also working on all mirrors by default.

See https://github.com/serayuzgur/crates/issues/197#issuecomment-1636997383

**Comment by inflation** [comment]
@serayuzgur Well, then it's unusable for me now. See my previous comment, I can reach whatever network the server is sitting but not itself. It seems like a misconfiguration than my ISP.

**Comment by ssrlive** [comment]
yes. I'm in china. so I have to modify `hosts` file to avoid dns pollution.

and here is the crates plugin settings
![image](https://github.com/serayuzgur/crates/assets/30760636/d5e5b59e-f108-4594-aa72-9b7e1036828a)


> ... Do you have any specific settings related to it, such as a proxy or other configurations?

**Comment by serayuzgur** [comment]
@inflation, it is possible. The server is hosted on DigitalOcean SF3. Are there any specific issues associated with this data center?

@ssrlive  maybe you have to configure your vsc like your browser, can you check ? https://code.visualstudio.com/docs/setup/network

**Comment by ssrlive** [comment]
Perfect. I hope you write it to you readme file.

![image](https://github.com/serayuzgur/crates/assets/30760636/7ca5154c-c348-4dd9-8347-17f57f063343)

**Comment by serayuzgur** [comment]
@ssrlive, please don't hesitate to create a pull request (PR). Feel free to explain it in your own words within the PR.

**Comment by azusachino** [comment]
I just switch back to 0.5.11, and it still works perfect fine.
![image](https://github.com/serayuzgur/crates/assets/18746830/17ccb412-598d-49a6-a0dc-5ec9f338d6f8)

**Comment by golanguage** [comment]
I hava this issue and have not any proxys. 
So back to 0.5.11 also.

**Comment by buf1024** [comment]
> yes. I'm in china. so I have to modify `hosts` file to avoid dns pollution.
> 
> and here is the crates plugin settings ![image](https://user-images.githubusercontent.com/30760636/254437337-d5e5b59e-f108-4594-aa72-9b7e1036828a.png)
> 
> > ... Do you have any specific settings related to it, such as a proxy or other configurations?

这样的解决办法并不好，因为在中国使用的境内的镜像加速，而设置全局代理，这加速镜像等于白干了。

**Comment by ssrlive** [comment]
My final solution in Windows. Please use sstap with a proxy server.
![image](https://github.com/serayuzgur/crates/assets/30760636/c05501dc-8cbe-420e-ad4c-647c9ebcd160)

**Comment by inflation** [comment]
After upgrading to `v0.6.2` and using the sparse index, this issue still presents. Versions with metadata still wrongly marked as pre-releases.

**Comment by BarbossHack** [comment]
Hi @inflation 
I don't have my laptop right now, so could you enable `crates.listPreReleases` in vscode settings, and see what happens ?

**Comment by inflation** [comment]
> Hi @inflation 
> I don't have my laptop right now, so could you enable `crates.listPreReleases` in vscode settings, and see what happens ?

It lists all versions with metadata, both "real pre-release" like `0.8.1-alpha+libjxl-0.8.1` and stable ones like `0.8.2+libjxl-0.8.2`. My guess is that it detects "-" as an identifier.

**Comment by BarbossHack** [comment]
> My guess is that it detects "-" as an identifier. 

Indeed, it must be something like this 👍 I will have time to look at this in a few days (if not already fixed in the meantime)

**Comment by BarbossHack** [comment]
https://github.com/serayuzgur/crates/blob/49e1d65545fd448ad2b5aff423a7e5c4c1388cda/src/core/fetcher.ts#L51

**Comment by golanguage** [comment]
For China user, 
this  setting is working.
"crates.indexServerURL": "https://rsproxy.cn/index/"

And https://rsproxy.cn/ shows how to use this mirror instead of officil crate index server for rustup and cargo.

**Comment by golanguage** [comment]
> > yes. I'm in china. so I have to modify `hosts` file to avoid dns pollution.
> > and here is the crates plugin settings ![image](https://user-images.githubusercontent.com/30760636/254437337-d5e5b59e-f108-4594-aa72-9b7e1036828a.png)
> > > ... Do you have any specific settings related to it, such as a proxy or other configurations?
> 
> 这样的解决办法并不好，因为在中国使用的境内的镜像加速，而设置全局代理，这加速镜像等于白干了。
"crates.indexServerURL": "https://rsproxy.cn/index/"
