### ISSUE TITLE
unable to verify the first certificate on all dependencies

### ISSUE THREAD

**Issue by ShayGusDataGen** [serayuzgur/crates#198]
**Describe the bug**
getting the following error when working in devcontainer:

Completed with errors
tokio: Error: unable to verify the first certificate
axum: Error: unable to verify the first certificate
serde: Error: unable to verify the first certificate
serde_json: Error: unable to verify the first certificate
tower-http: Error: unable to verify the first certificate
tower-cookies: Error: unable to verify the first certificate
lazy-regex: Error: unable to verify the first certificate
async-trait: Error: unable to verify the first certificate
surf: Error: unable to verify the first certificate
builder-pattern: Error: unable to verify the first certificate
tonic: Error: unable to verify the first certificate
tonic-reflection: Error: unable to verify the first certificate
prost: Error: unable to verify the first certificate
prost-serde: Error: unable to verify the first certificate
serde_cbor: Error: unable to verify the first certificate
serde_bytes: Error: unable to verify the first certificate
anyhow: Error: unable to verify the first certificate
proc-macro2: Error: unable to verify the first certificate
httpc-test: Error: unable to verify the first certificate
tonic-build: Error: unable to verify the first certificate

**To Reproduce**
1. Start a project in devcontainer
2. Add some dependencies
3. Error happening

**Expected behavior**
Expected to analyze the dependencies

**Screenshots**
![image](https://github.com/serayuzgur/crates/assets/66203291/cc55aac1-5b2d-40b1-a5f5-afdacd29182b)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version v0.6.0

**Additional context**
Cargo works fine

**Comment by franksacco** [comment]
I'm having the same issue using a Dev Container.
Rolling back to 0.5.11 from 0.6.0 fixed the problem temporarily.

**Comment by serayuzgur** [comment]
@ShayGusDataGen @franksacco  can you please take a look at https://stackoverflow.com/a/52699440 . I think it is related to your settings.

**Comment by franksacco** [comment]
Thanks @serayuzgur for your quick response.

I tried setting the `http.proxyStrictSSL` setting to `false` but that didn't fix the problem.

However, I find that the `https://api.crates-vsc.space` host is blocked by the company firewall. So, I will continue to use the 0.5.11 version of the extension to mitigate this issue.

**Comment by serayuzgur** [comment]
@franksacco  do you have any idea why it is blocked by firewall ? i have updated the ssl certificates, can you try again with v0.60
