### ISSUE TITLE
Glitchiness when editing Cargo.toml

### ISSUE THREAD

**Issue by lnicola** [serayuzgur/crates#20]
1.

![image](https://user-images.githubusercontent.com/308347/43156973-e5bd13ea-8f7b-11e8-930c-98b0a4c968d6.png)

2. Remove the current line:

![image](https://user-images.githubusercontent.com/308347/43156997-fb039378-8f7b-11e8-9d35-4a52d5da433a.png)

3. Press Enter, Home:

![image](https://user-images.githubusercontent.com/308347/43157013-07f0e50e-8f7c-11e8-8b0a-c7b924d0a092.png)

4. Undo twice:

![image](https://user-images.githubusercontent.com/308347/43157023-106421ce-8f7c-11e8-969b-6d93c03371bb.png)

**Comment by serayuzgur** [comment]
Hi @lnicola 
I think it will be fixed on save. Does it ?

**Comment by lnicola** [comment]
Yes, saving fixes it.
