### ISSUE TITLE
Invalid cert for api.crates-vsc.space

### ISSUE THREAD

**Issue by rickwebiii** [serayuzgur/crates#200]
**Describe the bug**
When I do something that should return version suggestions, I get an invalid cert.

> Completed with errors num: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: api.crates-vsc.space. is not in the cert's altnames: DNS:pxy.prd.live.c2szps.spscld.net

<img width="317" alt="image" src="https://github.com/serayuzgur/crates/assets/6934566/1e78ec45-c75d-400b-b89e-d73c090619da">

I also get a cert error if I try to navigate to this domain with Firefox.

**Comment by serayuzgur** [comment]
@rickwebiii , can you please check it again ?

**Comment by rickwebiii** [comment]
<img width="319" alt="image" src="https://github.com/serayuzgur/crates/assets/6934566/b8a4d36a-0c00-46e4-888b-c1b4abc95a68">

**Comment by rickwebiii** [comment]
Oh, I think that's some content filtering on my workplace's network. I'll investigate that more on my end.

**Comment by rickwebiii** [comment]
This was a problem on my end. Our ISP's malware filter blocked the site, but we were able to fix the issue.
