### ISSUE TITLE
Yanked version reappears when using local sparse index

### ISSUE THREAD

**Issue by inflation** [serayuzgur/crates#210]
**Describe the bug**
`tracing 0.1.38` is yanked and appears in the suggestions.

**To Reproduce**
1. Add `tracing` to `Cargo.toml`
2. Hover over the item.

**Expected behavior**

**Screenshots**
<img width="197" alt="image" src="https://github.com/serayuzgur/crates/assets/2375962/5a6e3782-ec80-43c8-9262-1cb10a793624">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 13.5.2

**Additional context**

**Comment by BarbossHack** [comment]
Indeed, thank you for reporting it :+1:

**Comment by serayuzgur** [comment]
fixed with v0.6.3
