### ISSUE TITLE
Invalid cert for api.crates-vsc.space, again

### ISSUE THREAD

**Issue by EvysGarden** [serayuzgur/crates#222]
**Describe the bug**
vsc shows
```
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: api.crates-vsc.space. is not in the cert's altnames: DNS:camaflexbh.com.br, DNS:[www.camaflexbh.com.br](vscode-file://vscode-app/nix/store/h09jggrlcarrasa22qml4603mnr9gwk2-vscode-1.84.2/lib/vscode/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)
```

**To Reproduce**
1. Open any rst project with dependencies
or
1. Go to https://api.crates-vsc.space/

**Expected behavior**
ssl should be fine

**Screenshots**
![image](https://github.com/serayuzgur/crates/assets/92547295/04c727f5-2c75-4382-b47b-4469bd95420b)

**Desktop (please complete the following information):**
 - OS: NixOS 23.11 with Linux 6.1.65

**Additional context**
Happened before #200

**Comment by BarbossHack** [comment]
`api-crates-vsc.space` is not the default anymore since v0.6.2 (and api.crates-vsc.space website has apparently been deleted)

Try this : 
- Remove all `Crates` settings from your vsc settings.json
- Update to latest (v0.6.3)
- Restart vscode

**Comment by serayuzgur** [comment]
That domain is not working anymore. Please use sparse index.
