### ISSUE TITLE
Missing visibility of failing crates.io requests

### ISSUE THREAD

**Issue by userzimmermann** [serayuzgur/crates#23]
When some `creates.io` request is failing, e.g. due to missing internet connectivity or some non-existing crate name, the situation is just silently handled w/o showing an error notification and w/o removing the `Fetching crates.io` message in the status bar. So the user has no idea what's actually going on...

**Comment by serayuzgur** [comment]
Done,
Better status bar message 
Also added an error message box with a (wait for it...) retry command 😄
