### ISSUE TITLE
Suggests old version when newer alpha is being used

### ISSUE THREAD

**Issue by bspeice** [serayuzgur/crates#24]
**Describe the bug**
When using `futures-preview` (currently at release `0.3.0-alpha.2`) crates is suggesting that I instead use the `Latest: 0.2.2`. While I'm totally fine with the general suggestion to use 0.2.2 as the newest non-alpha version, I'd rather not have a warning for something that is ahead of it.

**To Reproduce**
1. Start a new project
2. Add `futures-preview = "0.3.0-alpha.2"` to the `[dependencies]` block

**Expected behavior**
Shows a thumbs up indicating I have a version newer than the latest.

**Screenshots**
![screenshot_20180812_150856](https://user-images.githubusercontent.com/1199853/44005449-a2d21812-9e41-11e8-9e9b-973d37fa799c.png)

And finally, thank you for this extension! I'm a huge fan.

**Comment by serayuzgur** [comment]
Hi @bspeice ,
Thanks for the detailed issue. As I understood you want to keep **crates.listPreReleases** setting *false* and make an exception for pre-release versioned dependencies.

I tought that it could end up with a confusion, don't you think so?

**Comment by bspeice** [comment]
I'm not sure this causes confusion - I still want the extension to suggest version 0.2.2, but if I manually choose to use a pre-release higher than that, that should be fine as well.

It's fine by me if you'd prefer to keep the current behavior, but my original expectation is that I would only be recommended to use the most recent released version if the version I'm actually using is behind that.
