### ISSUE TITLE
Spacing issues with inline dependencies

### ISSUE THREAD

**Issue by lnicola** [serayuzgur/crates#26]
![image](https://user-images.githubusercontent.com/308347/45374069-54d82f80-b5f1-11e8-93d8-0d0e03afa3d1.png)

**Comment by lnicola** [comment]
![image](https://user-images.githubusercontent.com/308347/45374120-7b966600-b5f1-11e8-9160-c0419ec3d905.png)

Maybe that's expected, then. I think empty decorators shouldn't take space, please close if you feel otherwise :smile:.

**Comment by serayuzgur** [comment]
I think you are right, thanks for the issue

**Comment by serayuzgur** [comment]
@lnicola please check 0.3.2. Thanks.

**Comment by lnicola** [comment]
I think there's still too much space with the decorator enabled, but it's fine without it. Good enough for me, thanks.
