### ISSUE TITLE
workspace references with paths are problematic 

### ISSUE THREAD

**Issue by softprops** [serayuzgur/crates#29]
**Describe the bug**

I've recently split up a cargo project into workspaces with a [cli package refering to a lib package](https://github.com/softprops/emoji-clock/blob/97e76362b7a30812598c2c15c6bcc96f0ee6a260/cli/Cargo.toml#L17) by path. When I remove the reference by path the crates ext is successful. When added back I get a stream of error dialogs about it failing and screen of flickering thumbs!

**To Reproduce**

Setup a cargo workspace project with at least two package and at least one package referencing another by path

**Expected behavior**

Crates extension understands that the dependency exists locally retry with error dialogs.

**Screenshots**
![screen shot 2018-10-09 at 2 12 40 pm](https://user-images.githubusercontent.com/2242/46689459-e2497800-cbcd-11e8-92fd-91c2e26650a8.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] osx
 - Version [e.g. 22] 0.3.2 (latest at this time )

**Additional context**

trying to split up a mono cargo package into separate lib and cli packages with a [workspace](https://doc.rust-lang.org/book/second-edition/ch14-03-cargo-workspaces.html)

**Comment by serayuzgur** [comment]
@softprops Please check v0.3.4

**Comment by softprops** [comment]
sweet thanks 👍
 
![screen shot 2018-10-23 at 2 02 18 pm](https://user-images.githubusercontent.com/2242/47380841-6589c400-d6cc-11e8-9519-31c5bef5bee4.png)

**Comment by softprops** [comment]
actually it I missed it. it still shows an error but doesn't retry so its less annoying. previously this would keep retrying causing the screen to flicker

![screen shot 2018-10-23 at 2 05 07 pm](https://user-images.githubusercontent.com/2242/47381009-cca77880-d6cc-11e8-888f-18c63841a91d.png)

I think this works well enough for me now. Feel free to reopen if you think it's still an issue for others

**Comment by softprops** [comment]
Cool. I'm all set then 👍 thanks again for this awesome extension. It's been very helpful for keeping me up to date

**Comment by serayuzgur** [comment]
@softprops  now it will not show errors for git or path dependencies. Please check 0.3.6
