### ISSUE TITLE
Incorrect version for dependancy if last key-value includes inline table

### ISSUE THREAD

**Issue by jonathanmcelroy** [serayuzgur/crates#30]
**Describe the bug**

In my table of dependencies, the last dependency points to a local project:
```
[dependencies]
clap = "*"
error_lib = { path = "error" }
```

The next dependancy table is for rusqlite, which has versions going up to 0.14.0:
```
[dependencies.rusqlite]
version = "*"
features = ["bundled"]
```

However, the extension does not understand that this is a new table and thinks we are looking for a dependency called version:
```
version = "*"    Latest: 3.0.0
```

**To Reproduce**
Use this minimal toml file:
```
[dependencies]
clap = "*"
error_lib = { path = "error" }

[dependencies.rusqlite]
version = "*"
features = ["bundled"]
```
Open with the extension installed and activated.

**Expected behavior**
I get the correct version number

**Screenshots**
![image](https://user-images.githubusercontent.com/5642506/47187732-ee82b300-d2fa-11e8-9797-aa57139e6662.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 0.3.3

**Additional context**
I went a head and looked at the code. It does not reset the isParsingKey flag after parsing an inline table.
https://github.com/serayuzgur/crates/blob/530d2e6e0f42a0e1cbbfe2273554f16b46371b7f/src/toml/parser.ts#L155-L157

**Comment by serayuzgur** [comment]
@jonathanmcelroy Please check v0.3.4

**Comment by jonathanmcelroy** [comment]
Works great! Closing the issue
