### ISSUE TITLE
Error Fetching Dependency

### ISSUE THREAD

**Issue by seven-two-eight** [serayuzgur/crates#31]
**Describe the bug**
vs code shows `Fetch Errors` for `crates` Extension

**To Reproduce**
1. Go to 'Cargo.toml'
2. Below `[dependencies]`, add new line `nom = "4.1.1"`
3. See vs code error popup.

**Expected behavior**
`crates` works before, which shows thumbs-up unicode char next to dependency version.

**Screenshots**
![image](https://user-images.githubusercontent.com/41600242/47527930-d4545200-d871-11e8-9cb5-114be0e863f1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Build 1803

**Additional context**
It was all right yesterday. The only manual change I made was enabling `Format on Save` feature of vs code, which doesn't seem to fix the issue if toggled back.

**Comment by serayuzgur** [comment]
Hi @seven-two-eight ,
Can you please check v0.3.5?

**Comment by seven-two-eight** [comment]
It works! Thanks!
