### ISSUE TITLE
Can't Change Version Twice in a Row Until First Saving the TOML File.

### ISSUE THREAD

**Issue by AlexLeung** [serayuzgur/crates#32]
**Describe the bug**
When I hover over the version of a crate, I see the list of possible versions to choose from as expected. Then I accidentally choose a version I didn't mean to choose. When hovering over the incorrect version, I still get the list as expected, but now I cannot select the correct version I originally meant to select. The only way I can select the correct version is if I save the file first.

**Expected behavior**
To be able to change the version as many times as I want without needing to save the .toml file between each selection.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.3.4

**Comment by serayuzgur** [comment]
@AlexLeung Can't reproduce the issue. Can you explain more or please share your VSC peferences.

**Comment by AlexLeung** [comment]
I will try and get video of the behavior.
VS Code: 1.28.2
Extension Version: 0.3.5

**Comment by AlexLeung** [comment]
It's an 11 MB video https://drive.google.com/file/d/18d00pyVqZUhASkRDxyG2PuoFktdF1Nzv/view?usp=sharing

**Comment by AlexLeung** [comment]
I'm in the process of learning how to debug vscode extensions, I can see if I can get any logging info on what's going on.

**Comment by serayuzgur** [comment]
Hi, can you check your preferences, what is the value of "files.autoSave" ?

**Comment by AlexLeung** [comment]
`"off"`

**Comment by AlexLeung** [comment]
Are the tests meant in the current repo meant to fail?
```
  Parser Tests
    √ Read File
    1) Read Tables
    √ Read Values
    2) Test Start & end
    √ FilterCrates


  3 passing (38ms)
  2 failing

  1) Parser Tests
       Read Tables:

      AssertionError [ERR_ASSERTION]: '[package]\r\nname = "asasas"\r\nversion = "0.14.0"\r\nreadme = "README.md"\r\n\r\n' == '[package]\r\nname = "asasas"\r\nversion = "0.14.0"\r\nreadme = "README.md'
      + expected - actual

       [package]
       name = "asasas"
       version = "0.14.0"
      -readme = "README.md"
      -
      +readme = "README.md

      at Context.<anonymous> (src\test\toml\parse.test.ts:57:14)

  2) Parser Tests
       Test Start & end:

      AssertionError [ERR_ASSERTION]: '"asasas"' == ' "asasas'
      + expected - actual

      -"asasas"
      + "asasas

      at Context.<anonymous> (src\test\toml\parse.test.ts:89:14)



Waiting for the debugger to disconnect...
```

**Comment by serayuzgur** [comment]
Hi, nope they pass normally. You need to modify test  if you modified the toml. Are you testing on windows? 
I tested these on linux and macos but not on windows. It may fail because of the new line char difference "\r\n"  

[Related link](https://stackoverflow.com/questions/7013034/does-windows-carriage-return-r-n-consist-of-two-characters-or-one-character)

**Comment by AlexLeung** [comment]
On second thought, I'm not so sure that change is enough on its own because when I remove the `isDirty` check then I can select new versions without saving, but sometimes when I switch between versions too quickly a quotation mark appears at the end of the line in the `TOML` file I'm editing.

**Comment by serayuzgur** [comment]
But if you remove isDirty check and start to type, it will trigger too many times which causes editor to lose responsiveness. I think we can call "save" after list replaces the text.

**Comment by AlexLeung** [comment]
In the default listener function, you can add a check so `if(editor)` becomes `if(editor && status.inProgress)`

**Comment by AlexLeung** [comment]
It'd be nice to come up with a way that doesn't require saving each time. This could be done for example by only responding to text editor changes when `inProgress` is true.

**Comment by AlexLeung** [comment]
I guess in that case, you'd need to have something that changes inProgress to true whenever a new dependency is added, which could get a bit complicated.

**Comment by RensAlthuis** [comment]
Just ran in to this issue. Is there a reason you can't set inProgress to false at the end of the replaceVersion command similar to what you do in updateAll? It seems to fix the issue without having to force saving every time, though I suspect it can't be that simple.

**Comment by serayuzgur** [comment]
Hi @RensAlthuis 
I can't spend enough time on issues right now. So any PR's will welcome.
