### ISSUE TITLE
^ versions handled incorrectly

### ISSUE THREAD

**Issue by rbtcollins** [serayuzgur/crates#39]
A version in `Cargo.toml` like `^2` will match versions >=2 and <3. So it should show with a 👍 when the current version in crates.io is 2.5, but instead I get this:
```
pest = "^2.0"  Latest:2.1.0
pest_derive = "^2.0" Latest:2.1.0
```

However, cargo build is actually using 2.1.0.

**Comment by serayuzgur** [comment]
Hi @rbtcollins 
When I check crates.io it shows 2.1.0 . Please check from crates.io [link](https://crates.io/search?q=pest)

Please do not forget this plugin only fetches versions from crates.io

**Comment by rbtcollins** [comment]
I think you've misunderstood the bug report. I agree that `2.1.0` is what crates.io shows. The defect is that the matching algorithm for determining whether the dependency version is up to date in `Cargo.toml` is incorrect. 

`^` means 'match major version`. (Actually its more subtle than that, but this report isn't about versions less than 1.

Here is the current behaviours with pest:

| Cargo.toml | vscode-crates output | Cargo uses version
| --- | --- | ---
| "2.0" | Latest:2.1.0 | 2.1.0
| "^2.0" | Latest:2.1.0 | 2.1.0
| "2" |  👍  | 2.1.0
| "2.1" | 👍  | 2.1.0
| "~2.0" | Latest:2.1.0 | 2.0.2

This doesn't make sense to me: Only the last one is building with a non-latest version, but two of them show the "Latest" warning to encourage updating, even though thats not needed. From a cargo-semver perspective the first three entries are all identical: they all specify anything >= 2 but less than 3. Why is crates showing these warnings?
