### ISSUE TITLE
version list is broken

### ISSUE THREAD

**Issue by reuvenpo** [serayuzgur/crates#4]
when viewing the version list with crates 0.0.11 and with VSCode 1.24, the version list shows the version numbers, but also what appears to be the code that is responsible for the clicking functionality. for example, for `serde`, The list looks something like this:

Available Versions

* [1.0.66](command:crates.replaceVersion?{"item":"serde = "1.0.66"","start":116,"end":132})
* [1.0.65](command:crates.replaceVersion?{"item":"serde = "1.0.65"","start":116,"end":132})
* [1.0.64](command:crates.replaceVersion?{"item":"serde = "1.0.64"","start":116,"end":132})
* [1.0.63](command:crates.replaceVersion?{"item":"serde = "1.0.63"","start":116,"end":132})
* [1.0.62](command:crates.replaceVersion?{"item":"serde = "1.0.62"","start":116,"end":132})
... etc.

**Comment by reuvenpo** [comment]
just for completeness, I'm running VSCode inside `flatpak` on a linux machine, but i don't believe this is the issue

**Comment by BjoernPetersen** [comment]
I think this is what's causing the issue: https://github.com/Microsoft/vscode/issues/33577

**Comment by serayuzgur** [comment]
Hi @reuvenpo ,
Thanks for the issue. It was caused by the MarkDownString lin usage. With the new VSC (1.24) json data cracks markdown. Now it is url encoded and fixed.  

@BjoernPetersen , thanks for the idea.

**Comment by reuvenpo** [comment]
Works like a charm<sup>1</sup>, thanks :)

<sup>1</sup> well, isn't programming pretty much just spellcasting anyways?
