### ISSUE TITLE
alternative registries are not taken into account

### ISSUE THREAD

**Issue by arturoc** [serayuzgur/crates#41]
Crates from alternative registries are parsed as comming from crates.io so the versions shown are from crates.io instead of the altenarive registry but also if the package doesn't exist in crates.io an error is shown every time the file is modified

**To Reproduce**

Add a crate from an alternative registry which has a different max version there than in crates.io or doesn't exist in crates.io, only in the alternative registry

**Expected behavior**
Ideally that versions are parsed from the alternative registry but at least that the alternative registry is detected so those crates don't show any max version and no error is shown if they don't exist in crates.io as happens with packages from git sources

**Platform:**
 - OS: linux (should happen in other platforms)
 - Version 0.3.7

**Additional context**
alternative registries are still not stable but will be in the next release, 1.34

**Comment by serayuzgur** [comment]
Hi @arturoc ,
Thanks for the issue.

**Comment by serayuzgur** [comment]
please check v0.4.3

**Comment by 0xpr03** [comment]
Yeah currently it'd already be great if one could silence git-based errors.
