### ISSUE TITLE
Plugin sends too many concurrent requests to crates.io

### ISSUE THREAD

**Issue by sgrif** [serayuzgur/crates#42]
We're periodically seeing abnormal spikes in traffic that originate from this plugin. It appears to send a request for every crate it wants to know about concurrently, with no limiting of any kind in place. We're frequently seeing upwards of 50+ concurrent requests from the same IP identifying as this plugin.

This is in violation of [the crates.io crawler policy](https://crates.io/policies#crawlers). At minimum these requests need to be sent serially rather than in parallel.

Thank you for setting a proper user-agent header so I am able to reach out without having to resort to blocking traffic

**Comment by serayuzgur** [comment]
@sgrif Thanks for reaching out. Next version will fix this asap.

**Comment by serayuzgur** [comment]
@sgrif , I developed the fix. It calls in serial but there is a performance problem now. It takes too long to fetch all information in serial and this is not very good for developer experience.  I think we should find another way. Is there any other service to fetch multiple crate info at one request ?

**Comment by sgrif** [comment]
Depending on the information you need, you can probably get everything you need from the index and not hit the API at all

**Comment by serayuzgur** [comment]
So what you are suggesting is using github api on crates.io-index repository master branch and fetching all dependency versions from there. 
I got two questions. 
1. Are you sure it is reliable to to do this like that? Github can also close access to api and it is not even under our control. 
2. I saw your [PR](https://github.com/rust-lang/crates.io/pull/1670) and it seems a better approach than blocking concurrent requests. Can we set a limit for concurrent requests? Maybe 4

**Comment by sgrif** [comment]
> So what you are suggesting is using github api on crates.io-index repository master branch and fetching all dependency versions from there.

I'd just clone the repo

> Are you sure it is reliable to to do this like that? Github can also close access to api and it is not even under our control.

I'm not sure what your point is here? The crates.io API is also not under your control.

> I saw your PR and it seems a better approach than blocking concurrent requests. Can we set a limit for concurrent requests? Maybe 4

That PR doesn't have anything to do with concurrent requests. Adding global limits is something we're looking into doing in the future, but that doesn't change the fact that our policies are what they are.

**Comment by serayuzgur** [comment]
> I'd just clone the repo

Ok I got the idea, but it will take some time to implement. Thanks.

> I'm not sure what your point is here? The crates.io API is also not under your control.

I said **our**  like we are on the same team , both serving to the rust community.

> That PR doesn't have anything to do with concurrent requests. Adding global limits is something we're looking into doing in the future, but that doesn't change the fact that our policies are what they are.

My mistake , I tought you were dealing with some performance issues on DB.

Thanks for your time and ideas.

**Comment by serayuzgur** [comment]
please check v0.4.0
