### ISSUE TITLE
Versions shown in the wrong order

### ISSUE THREAD

**Issue by Diggsey** [serayuzgur/crates#43]
**Describe the bug**
Earlier versions appear as "newer" than later versions if they were published to crates.io later.

**To Reproduce**
Add `aerosol` as a dependency - 0.2.0 appears as older than 0.1.3. (Because 0.1.3 was published more recently)

**Expected behavior**
0.2 should appear newer than 0.1.3

**Comment by serayuzgur** [comment]
Thanks for the issue. Please check version 0.4.1

**Comment by Diggsey** [comment]
Fixed thanks!

**Comment by normano** [comment]
Hmm, if you check serde_json, you'll see that the expected way is that 1.0.9 is older than 1.0.39, but this extension shows it the other way around in version 0.4.1. Might want to look into using something like https://www.npmjs.com/package/compare-versions
