### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by d8aninja** [serayuzgur/crates#49]
- Issue Type: `Performance`
- Extension Name: `crates`
- Extension Version: `0.4.2`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/pllllth/serayuzgur.crates-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by serayuzgur** [comment]
Hi @d8aninja ,
Extension uses CPU to parse toml and fetch dependency versions. It must be for a short time.  Do you agree with that ?

**Comment by serayuzgur** [comment]
inactive
