### ISSUE TITLE
Support for [dev-dependencies] crates parsing

### ISSUE THREAD

**Issue by zigguratvertigo** [serayuzgur/crates#5]
This vscode extension is great at parsing crates specified in [dependencies]. Unfortunately it seems to ignore crates specified in [bin-dependencies]. Any plans on supporting this?

**Comment by serayuzgur** [comment]
Hi, thanks. I developed it at my free times so i focused on what is most commonly used. If it is needed, why not, we can support it. Also PR's are welcome 😄  Can you please provide a sample toml ?

**Comment by serayuzgur** [comment]
@zigguratvertigo can you please check version 0.1.1
