### ISSUE TITLE
Extension on remote ssh server use proxy settings of local machine

### ISSUE THREAD

**Issue by kigawas** [serayuzgur/crates#51]
See https://github.com/microsoft/vscode-remote-release/issues/957

**Comment by serayuzgur** [comment]
@kigawas  is it related with [this](https://github.com/request/request-promise/issues/130) ?
Do you have a quick solution? Nowadays I don't have much time so any PRs are welcome.

**Comment by kigawas** [comment]
@serayuzgur 
Not exactly.
I don't see any proxy settings in this repo, and I'm not sure whether it's the default behavior of `request-promise`
