### ISSUE TITLE
Buggy rendering for parameterized dependencies

### ISSUE THREAD

**Issue by tracker1** [serayuzgur/crates#52]
**Describe the bug**

**To Reproduce**
I started with the yew dashboard example's cargo file.

```
[package]
name = "dashboard"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
serde = "1"
serde_derive = "1"
yew = { path = "../..", features = ["toml"] }
```

I wanted to replace it with `version="1"` to try and get a list instead of the `path=` parameter, and the rendering got a bit borked, to say the least.

**Expected behavior**
I'd expected the rendering to not bork... Also, while editing the format for the file may have been invalid, which may have effected things.

**Screenshots**

<img width="607" alt="Screen Shot 2019-08-25 at 15 35 58" src="https://user-images.githubusercontent.com/444316/63656863-9dc7bc00-c74e-11e9-9525-84e86f2382a2.png">

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Version 10.13.3

**Comment by serayuzgur** [comment]
@tracker1  thanks
