### ISSUE TITLE
Uppercase key seems to be causing an error

### ISSUE THREAD

**Issue by CugeDe** [serayuzgur/crates#56]
**Describe the bug**
I am not sure of the reason but it looks like using a dependency with a key starting with an uppercase char causes an error.

![Error](https://user-images.githubusercontent.com/12921065/66132950-29f2bc00-e5f6-11e9-9a75-869a3e5ba26b.png)

**To Reproduce**
Just try with Inflector as dependency (with uppercase 'I').

```toml
# ...

[dependencies]
Inflector = "0.11.4"
# ...
```

**Desktop (please complete the following information):**
- OS: ArchLinux
- Rust: 1.39.0-nightly
- Cargo: 1.39.0-nightly

**Comment by serayuzgur** [comment]
@CugeDe thanks for the issue.
