### ISSUE TITLE
Improve version resolution

### ISSUE THREAD

**Issue by lnicola** [serayuzgur/crates#6]
`log = "0.4"` should be the same as `log = "0.4.2"`.

**Comment by serayuzgur** [comment]
Hi @lnicola , 
Can you please explain why giving full versions is not suitable for your case. According to me exact match is safer.

**Comment by serayuzgur** [comment]
@lnicola thanks for the brief description. I am planning this to 0.1.2

**Comment by lnicola** [comment]
To be fair, you probably shouldn't implement the complete resolution algorithm. If I use `futures = "< 0.2"`, it should still suggest upgrading to `0.2`. That's why I'd suggest to use the simpler solution of ignoring the patch path. Maybe someone else has a better idea?

**Comment by serayuzgur** [comment]
@lnicola , to be clear  are these scenarios ok for you ?
currentVersion: 4 
latest 4.1.0 
plugin will show OK

currentVersion: 4.1
latest 4.1.2 
plugin will show OK

currentVersion: 4.1
latest 4.2.2 
plugin will show 4.2.2 

currentVersion: 4
latest 5.2.1
plugin will show 5.2.1

**Comment by lnicola** [comment]
> currentVersion: 4
> latest 4.1.0
> plugin will show OK
>
> currentVersion: 4.1
> latest 4.1.2
> plugin will show OK

Yes.

> currentVersion: 4.1
> latest 4.2.2
> plugin will show 4.2.2

For me, yes; according to semver, they're the same, so someone else might complain.

> currentVersion: 4
> latest 5.2.1
> plugin will show 5.2.1

Yes.

**Comment by serayuzgur** [comment]
@lnicola Let them have this freedom and leave like that 😄 
Please check 0.2.0

**Comment by lnicola** [comment]
Cool, seems to work!
