### ISSUE TITLE
Move from GitHub v3 API to v4 to reduce risk of too many queries

### ISSUE THREAD

**Issue by jonathandturner** [serayuzgur/crates#62]
I'm seeing that we're still hitting the rate limit for nushell (https://github.com/nushell/nushell).

Something I've noticed using both v3 and v4 APIs for GitHub is that with v3 it's pretty easy, even with authentication, to hit your rate limit. Since you can only send one query at a time, you end up naturally hitting it unless you add artificial delays in the queries.

At one point working with the GitHub API to track language popularity, I moved my tool over to the v4 APIs. Here's an example of the kind of query string I'd use:

```
{"query": "query { lang0: search(type:ISSUE, query: \"language:JavaScript type:pr created:2019-11-04..2019-11-11\") { issueCount } lang1: search(type:ISSUE, query: \"language:Java type:pr created:2019-11-04..2019-11-11\") { issueCount } }"}
```

Which is this bit of GraphQL:

```
query { lang0: search(type:ISSUE, query: "language:JavaScript type:pr created:2019-11-04..2019-11-11") { issueCount } lang1: search(type:ISSUE, query: "language:Java type:pr created:2019-11-04..2019-11-11") { issueCount } }
```

When that's run, each answer gets a label attached to it that can be queried back out. This lets you run a bunch of queries all at once and it's generally much easier to stay in your rate limit this way (v4 rate limits work differently than v3).

**Comment by serayuzgur** [comment]
@jonathandturner  at v3 I am using content api  
`/contents/${decidePath(name)}` 
with 
` Accept: "application/vnd.github.VERSION.raw"`

I looked but couldn't find equivalent query at v4. Did you ?

**Comment by jonathandturner** [comment]
```
# Type queries into this side of the screen, and you will 
# see intelligent typeaheads aware of the current GraphQL type schema, 
# live syntax, and validation errors highlighted within the text.

# We'll get you started with a simple query showing your username!
query {
  repository(owner:"nushell", name:"nushell") {
      object(expression: "master:") {
      ... on Tree{
        entries{
          name
          type
          mode
        }
      }
    }
  } 
}
```

If you want, say, the contents of the Cargo.toml file, you can do:

```
query {
  repository(owner:"nushell", name:"nushell") {
      object(expression: "master:Cargo.toml") {
      ... on Blob{
        text
      }
    }
  } 
}
```

**Comment by serayuzgur** [comment]
@jonathandturner thanks, i will check it , if the new cost algo is more suitable for our scenario, i will migrate

**Comment by jonathandturner** [comment]
Sounds good. You might also be able to do multiple queries in one call like I show in the first comment on this thread, so you could get multiple Cargo.toml's at the same time.

**Comment by serayuzgur** [comment]
for other people to know what we talked about 
[v4 rate limit](https://developer.github.com/v4/guides/resource-limitations/#rate-limit)

**Comment by jonathandturner** [comment]
Good idea.

Here's multiple requests in one query:
```
query {
  nushell: repository(owner:"nushell", name:"nushell") {
      object(expression: "master:Cargo.toml") {
      ... on Blob{
        text
      }
    }
  }
  
  rust:  repository(owner:"rust-lang", name:"rust") {
      object(expression: "master:Cargo.toml") {
      ... on Blob{
        text
      }
    }
  }
}
```

**Comment by serayuzgur** [comment]
This issue is closing since we will add support for local cargo registry GitHub api will be fallback option but thanks for all the effort
