### ISSUE TITLE
pin-utils: no versions found

### ISSUE THREAD

**Issue by jonathandturner** [serayuzgur/crates#63]
**Describe the bug**
The `pin-utils` crate can't be found by the crates plugin.

**To Reproduce**
1. Add `pin-utils = "0.1.0-alpha.4"` to your dependencies

**Expected behavior**
The crates.io version to be found

**Additional context**
This is part of the dependencies for nushell(https://github.com/nushell/nushell). Not sure if it's related to other things in the Cargo.toml.

**Comment by serayuzgur** [comment]
Please check list pre-releases from preferences
![image](https://user-images.githubusercontent.com/4561330/76768033-8401cb00-67ab-11ea-9634-22443184663c.png)
