### ISSUE TITLE
should not send requests when Cargo.toml is invalid

### ISSUE THREAD

**Issue by kigawas** [serayuzgur/crates#64]
Say I'm editing a Cargo.toml file and I save it before finishing editing it.

At this time, I may not want it to check the version since the toml file is invalid

**Comment by serayuzgur** [comment]
@kigawas It parses toml and does not handle it as a whole document. I follow fetch and decorate whatever you can. So please do not forget until you close the toml it does not fetch already fetched ones, they are cached.
