### ISSUE TITLE
Plugin shows yanked crates as latest

### ISSUE THREAD

**Issue by repi** [serayuzgur/crates#7]
**Describe the bug**
If you have a dependency on a crate where the latest version of that crate have been yanked, the crates plugin will show that the latest yanked version is available, instead of latest available version.

**To Reproduce**
Add a dependency on latest available futures crate: 
```
futures = "0.1.21"
```
Note that the crates plugin shows that a later 0.2.1 version is available, even though it has been yanked
<img width="285" alt="screen shot 2018-07-02 at 15 00 14" src="https://user-images.githubusercontent.com/1262692/42165557-adceeb54-7e08-11e8-97ae-3bb834d5874d.png">

**Expected behavior**
I would expect the plugin to ignore yanked versions of crates and only show the latest actually available crate.

This is not really a major issue, but thought I would report it. Thanks for an awesome plugin!

**Comment by serayuzgur** [comment]
Hi @repi ,
Thanks for the issue. I think you are totally right and yanked versions will be hidden on the next release.

**Comment by serayuzgur** [comment]
@repi Please check 0.2.0
