### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by szelenkov** [serayuzgur/crates#70]
- Issue Type: `Performance`
- Extension Name: `crates`
- Extension Version: `0.4.7`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.42.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Serhiy\serayuzgur.crates-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by serayuzgur** [comment]
Hi @szelenkov,
Can you please explain what happened and please attach the cpu profile. For further issues please provide more information.

**Comment by szelenkov** [comment]
Hi Seray.
I was trying to use your extension. restart code , got popup message and
submit an error message.
Since code really slow down , had to uninstall extension, now code
works fine.

**Comment by serayuzgur** [comment]
I am sorry but , have to close this issue since the information provided is not enough. Sorry you couldn't benefit the extension.
