### ISSUE TITLE
Error: The requested blob is too large to fetch via the API

### ISSUE THREAD

**Issue by LucianoBestia** [serayuzgur/crates#71]
I use Crates 0.4.7. VSCode Extension on windows with Remote -WSL. The code is actually inside Windows Subsystem for Linux (Debian 10 backend) and only the frontend is in windows. 
In my cargo.toml the  Crates Extension  draws a red exclamation sign near web.sys like this:

[dependencies.web-sys]
version = "0.3.27"   **!**
features = [
  "AbortController",
  "console",
....

The error msg is:
web-sys: StatusCodeError: 403 -
 "{"message":"This API returns blobs up to 1 MB in size. 
 The requested blob is too large to fetch via the API, 
 but you can use the Git Data API to request blobs up to 100 MB in size.",
 "errors":[{"resource":"Blob","field":"data","code":"too_large"}],
 "documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents\"}"

Is it possible to correct this error?

Thanks

**Comment by serayuzgur** [comment]
wow it is , but it may take some time. Also I am planning to code my own index server for version fetching but not enough sponsors right now so I have to check Data API first.

**Comment by LucianoBestia** [comment]
Do you use this api ?
https://crates.io/api/v1/crates/web-sys

**Comment by serayuzgur** [comment]
I was using it before then crates.io stated that i should use (github) index or extension will be banned because of call rates.

**Comment by serayuzgur** [comment]
I am referencing @LucianoBestia  's code to make it visible more [cargo_reg_local](https://github.com/LucianoBestia/cargo_reg_local)

**Comment by Mubelotix** [comment]
Why is this issue closed? The problem has not been fixed.

**Comment by LucianoBestia** [comment]
Sorry for closing. I was just clumsy. I should reopen it.

**Comment by serayuzgur** [comment]
I have merged a PR about using local repository index but it is not ready to ship yet. This will be available with v0.5.0

**Comment by serayuzgur** [comment]
check  version 0.5.0 please

**Comment by LucianoBestia** [comment]
It works great. Thank you.
The problematic [dependencies.web-sys] now work flawlesly.

![image](https://user-images.githubusercontent.com/31509965/82907568-66f43000-9f84-11ea-94c3-6ee124a92286.png)

**Comment by Mubelotix** [comment]
The issue is back. You should reopen @LucianoBestia

**Comment by serayuzgur** [comment]
@Mubelotix  please use local repository index

**Comment by Mubelotix** [comment]
How is this possible?

**Comment by serayuzgur** [comment]
<img width="1250" alt="Screen Shot 2020-07-01 at 11 37 15" src="https://user-images.githubusercontent.com/4561330/86222677-3c9f1f00-bb8f-11ea-9508-221e5a554c81.png">
