### ISSUE TITLE
Goto Docs

### ISSUE THREAD

**Issue by LucianoBestia** [serayuzgur/crates#72]
It would be very helpful to have Goto Docs in the Crates Extension.
It should open the link 
https://docs.rs/ **cratename**
example:
the latest version
<https://docs.rs/wasm-bindgen-futures>
or the exact version
<https://docs.rs/wasm-bindgen-futures/0.4.8>
Image of the feature:
![crates](https://user-images.githubusercontent.com/31509965/72205500-4be1c180-34b6-11ea-98a0-9b7dd0d3057c.png )

**Comment by serayuzgur** [comment]
thanks for the issue. It is a nice feature.

**Comment by serayuzgur** [comment]
@LucianoBestia  you can check version 0.4.8 and thanks for the idea

**Comment by LucianoBestia** [comment]
Thank you. Looks great. Very useful.

**Comment by LucianoBestia** [comment]
After using it for an extended time, I now think the UI is too crowded.
I think that only the docs for the current and latest version are needed.
The developer cares only about this 2 versions.
From there it is possible to open other docs.
I suggest to make it leaner like this:

![image](https://user-images.githubusercontent.com/31509965/82906688-3c55a780-9f83-11ea-9812-c345e42339ff.png)

**Comment by serayuzgur** [comment]
Hi, thanks for the advice. I agree with you it is also disturbing me. Let's think a little bit about a new design, maybe we can do it all better not just docs links

**Comment by LucianoBestia** [comment]
I am thinking aloud now.
What is important when the developer wants to change the version of a dependency?
He should read some information what changed and if there are problems with the new version.
Reading the documentation is fine, but it is just like commercials. The author will always say the best for his product. Sometimes he does not know better. Sometimes he is lazy. I don't want to go in extreme where evil people want to do harm. That is rare, but is not impossible.

I like the idea of cargo-crev: 
https://github.com/crev-dev/cargo-crev
a system of trusted reviews from other developers. If enough people say a version is ok it is probably ok. If some people say an explicit version has big problems it probably has and should be avoided. There are reviews, issues and advisories in cargo-crev.

I am building (slowly) a web interface cargo_crev_web. Try it here:
https://bestia.dev/cargo_crev_web/query/num-traits

I think that your extension `crates` is the best place for the developer to find this information
before he actually updates the version of a dependency.

**Comment by serayuzgur** [comment]
@LucianoBestia , currently cargo_crev_web is in development and it is not a good idea until it is stable. But I changed some ui as you suggested.

- Only latest and current shows docs link
- Latest is the first so no indicator.
- Current is bolded to show it is the current version.

What do you think?

<img width="400" alt="Screen Shot 2020-06-08 at 15 37 14" src="https://user-images.githubusercontent.com/4561330/84031201-f1358e80-a99d-11ea-9250-f4bae00ea010.png">

**Comment by LucianoBestia** [comment]
Looks great ! Clean and effective.
cargo_crev_web has now a stable url, try it: 
https://web.crev.dev/rust-reviews/
The basic functionality to show single crate reviews is complete and stable. 
There will be changes, but in other parts of the web app. It is my project so I need to promote it.
I would appreciate if you give it a look. Thanks.

**Comment by serayuzgur** [comment]
@LucianoBestia if you say so I can put a link to the top like "Check Reviews"

**Comment by LucianoBestia** [comment]
Yes.
That would be great !
Thanks.

>

**Comment by serayuzgur** [comment]
I think it is clean, what do you say?
<img width="290" alt="Screen Shot 2020-06-09 at 12 54 10" src="https://user-images.githubusercontent.com/4561330/84133887-6b265000-aa50-11ea-9c76-688ec4006a9d.png">

**Comment by LucianoBestia** [comment]
Title and link in one line looks too crowded. They are not inseparable by their meaning.
I think it should look better in two lines.

**Comment by serayuzgur** [comment]
According to me two line is too negative spaced and kills the focus on the version links. 
Also please note that i am navigating to crate reviews not to a single version

<img width="251" alt="Screen Shot 2020-06-14 at 13 50 51" src="https://user-images.githubusercontent.com/4561330/84591320-1155c980-ae46-11ea-9ffa-85e297603f82.png">

<img width="184" alt="Screen Shot 2020-06-14 at 13 48 35" src="https://user-images.githubusercontent.com/4561330/84591269-c045d580-ae45-11ea-86d3-ec46556ccd2e.png">

**Comment by LucianoBestia** [comment]
Yes. It is too spaced in 2 lines.
It is better in one line.
Have you tried the Rust reviews?
I have there links to crates.io, lib.rs and docs.rs. There is only 900 reviews now, but after the announcement of the web page in user.rust-lang, I expect more involvement.

**Comment by serayuzgur** [comment]
I tried it and  it is nice to read real experiences. Thanks for the tool. So I am closing this issue since we agreed on some point. It has to wait next version of crates since there is a important issue. #82
