### ISSUE TITLE
inkwell: "No versions found"

### ISSUE THREAD

**Issue by mfdorst** [serayuzgur/crates#73]
**Describe the bug**

Crates reports "No versions found" for `inkwell = "0.0.0"`
This is odd, since cargo has no problem finding and installing the crate. Perhaps it is due to the unconventional all-zero version number?

**To Reproduce**

In `Cargo.toml`:
```toml
[dependencies]
inkwell = "0.0.0"
```

**Expected behavior**
The crate should be found.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.14 Mojave

**Comment by serayuzgur** [comment]
Thanks for the issue , i will check it

**Comment by serayuzgur** [comment]
@mfdorst  you can check version 0.4.8
