### ISSUE TITLE
Crates doesn't work with VS Code *INSIDER*

### ISSUE THREAD

**Issue by rucoder** [serayuzgur/crates#76]
**Describe the bug**
1. install an extension
2. try to type anything in cargo.toml
3. "No suggestions" is displayed when hitting ctrl+space

I understand that 'insider' version might not be a high priority but this is what will become a stable version. Fixing this issue on insider might avoid this bug in future on stable

**Desktop (please complete the following information):**
 - OS: Both Windos and Linux
 - Version 0.4.9
- Visual studio Code Insider v 1.44.0-insider

**Comment by serayuzgur** [comment]
Hi. this extension is not working like that for now. You can type an empty dependency than hover it to see versions.

**Comment by rucoder** [comment]
Well... the whole point was to get suggestions for crates names. Otherwise, I can just go to creats.io :)

**Comment by serayuzgur** [comment]
Maybe for you but also tracking dependencies is hard. I will add suggestions later for now only version list and doc.rs links.
Thanks.
