### ISSUE TITLE
Fails to fetch Cargo.toml

### ISSUE THREAD

**Issue by JonnyCodewalker** [serayuzgur/crates#78]
**Describe the bug**
The extensions fails to fetch Cargo.toml when starting VSCode or when using the comand crates.retry.
**To Reproduce**
cargo init test_crates
code-oss test_crates
install extension
try to add a crate to cargo.toml (eg. rand v. 0.7.3)

**Expected behavior**
Fetching crates, showing all available versions of the crate etc.

**Screenshots**
https://i.imgur.com/B2DPbBo.png

**Desktop (please complete the following information):**
 - OS: Solus 4.1
 - Crates version 0.4.8
 - VSCode version 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300dddx64)

**Comment by serayuzgur** [comment]
Hi, cannot reproduce this issue , need more info please.
