### ISSUE TITLE
Store authentication token in globalState

### ISSUE THREAD

**Issue by lnicola** [serayuzgur/crates#79]
**Is your feature request related to a problem? Please describe.**
I store my dotfiles in a GitHub repository and I don't want to add a personal authentication token to my `settings.json`.

**Describe the solution you'd like**
The extension could probably use [`ExtensionContext.globalState`](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext.globalState) to store the token. 

**Describe alternatives you've considered**
Do nothing since querying the GitHub API seems to be soft-deprecated since a couple of hours ago.

**Additional context**
N/A

**Comment by serayuzgur** [comment]
As you said , you can use cargo registry.

**Comment by lnicola** [comment]
I haven't checked how it works? Does the extension trigger an update of the cargo index? I never know when `cargo` does it automatically.

Apparently `cargo install lazy_static` is the way to force an update (it won't compile the crate).

**Comment by serayuzgur** [comment]
@lnicola actually it just reads it. You have to manage the registry manually. Maybe we can open a new issue and discuss how and when to update registry.
