### ISSUE TITLE
Exclamation marks on dependencies when user profile folder contains space

### ISSUE THREAD

**Issue by earthengine** [serayuzgur/crates#83]
**Describe the bug**
In Windows 10, the user profile folder ("C:\Users\The User") can contain space. Crate 0.5.0 cannot handle this properly and will result in showing exclamation marks instead of the thumb emoji. 

**To Reproduce**
1. Make sure the current user's profile folder contains a space.
2. Create a new crate and open `Cargo.toml`.
3. Add a new dependency
4. Observe the exclamation mark on the right, and when move mouse over it it shows error message like

```
Error: Command failed: git --no-pager --git-dir=C:\Users\The User.cargo\registry\index\github.com-1ecc6299db9ec823.git show origin/master:pi/n-/pin-project git: 'User.cargo\registry\index\github.com-1ecc6299db9ec823.git' is not a git command. See 'git --help'. *
```

**Expected behavior**
Show a normal thumb emoji on the right, or if not the latest version, the latest version of the crate.

**Desktop:**
 - OS: Windows 10
 - Version 0.5.0

**Comment by serayuzgur** [comment]
mentioned at #82
