### ISSUE TITLE
Doesnt' seem to work with the latest vscode 1.46.1

### ISSUE THREAD

**Issue by pasviegas** [serayuzgur/crates#84]
**Describe the bug**
I tried to install the latest version in VSCode 1.46.1. The extension gets automatically disabled and I am not able to enable it. 

Looking at the debug console I see that the extension is set to work with VSCode 1.45.1 and in package.json the "engine" property is set to 1.45.1 too.

**To Reproduce**
1. Open VSCode with the extension installed.
2. Click to view the disabled extensions.
3. Crates extensions will be disabled with no option to enabled it.

**Expected behavior**
The extension is enabled in VSCode's extension view.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Version: VSCode 1.46.1; Crates 0.5.0

**Comment by serayuzgur** [comment]
v5.0.1 will fix this
