### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ararunaufc** [serayuzgur/crates#85]
- Issue Type: `Performance`
- Extension Name: `crates`
- Extension Version: `0.5.1`
- OS Version: `Linux x64 5.6.16-1-MANJARO`
[serayuzgur.crates-unresponsive.cpuprofile.txt](https://github.com/serayuzgur/crates/files/4855777/serayuzgur.crates-unresponsive.cpuprofile.txt)

- VSCode version: `1.46.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/araruna/serayuzgur.crates-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by serayuzgur** [comment]
using  local registry or GitHub API?
