### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Dim4IQ** [serayuzgur/crates#87]
- Issue Type: `Performance`
- Extension Name: `crates`
- Extension Version: `0.5.1`
- OS Version: `Linux x64 5.6.16-1-MANJARO`
- VSCode version: `1.45.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/dim4iq/serayuzgur.crates-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by serayuzgur** [comment]
Github API or local registry?

**Comment by serayuzgur** [comment]
@Dim4IQ  can you please check it with the 0.5.2

**Comment by Dim4IQ** [comment]
It was automatic report by VSCode, so I don't even know details
