### ISSUE TITLE
Various glitchiness with unparseable TOML

### ISSUE THREAD

**Issue by lnicola** [serayuzgur/crates#9]
1.
![image](https://user-images.githubusercontent.com/308347/42182299-0a62b942-7e3e-11e8-86a5-a9a7ae36550e.png)

2.
![image](https://user-images.githubusercontent.com/308347/42182306-1029314e-7e3e-11e8-806d-54079e962f55.png)

3.
![image](https://user-images.githubusercontent.com/308347/42182315-1425ac1e-7e3e-11e8-93d3-65e6de6d839d.png)

4. 
![image](https://user-images.githubusercontent.com/308347/42182352-2faf09ee-7e3e-11e8-88de-52422a6efe61.png)

This is already mentioned in the README, of course.

**Comment by serayuzgur** [comment]
Hi @lnicola ,
What kind of action do you suggest. I can notify user at the status bar.

**Comment by lnicola** [comment]
I don't know, maybe stop updating or hide everything.

**Comment by serayuzgur** [comment]
Please check v 0.2.2

**Comment by lnicola** [comment]
This doesn't seem to work perfectly:

![image](https://user-images.githubusercontent.com/308347/42703773-d747041c-86cd-11e8-838e-3173e472ca1f.png)

(missing decorator)

It does refresh on save, though. I guess it's not too bad.

**Comment by lnicola** [comment]
> crates now decorates the toml file on each save. Not on every change.

Ah, okay. I didn't notice the toolbar and error message, though. There was a "TOML parse error" squiggly, but I think that's from the "Better TOML" extension.

**Comment by lnicola** [comment]
This was actually a poor idea. When you're adding a new dependency, `Cargo.toml` will be invalid, and the extension will show suggestions for the crate on the previous or next line:

![image](https://user-images.githubusercontent.com/308347/43157097-40400732-8f7c-11e8-9514-7996824110eb.png)
