### ISSUE TITLE
Incorrectly running on non-dependencies section of Cargo.toml

### ISSUE THREAD

**Issue by rylev** [serayuzgur/crates#94]
**Describe the bug**
The `cargo winrt` command uses the fact that `package.metadata` in Cargo.toml files can contain arbitrary data to encode which Windows Runtime packages should be downloaded from NuGet as dependencies for Rust based WinRT project. Unfortunately, the crates extension incorrectly views these as Cargo dependencies and tries to fetch information on them. 

**To Reproduce**
1.) Add the following to Cargo.toml:
```
[package.metadata.winrt.dependencies]
"Microsoft.Windows.SDK.Contracts" = "10.0.19041.1"
```
2.) Observe the `!` that appears next to the dependency.

**Expected behavior**
These dependencies should simply be ignored by the extension.

**Screenshots**
![caputre1](https://user-images.githubusercontent.com/1327285/87936332-f0127980-ca92-11ea-9afc-6eb1262be044.png)

**Desktop:**
 - OS: Windows 10
 - Version 0.5.2

**Comment by serayuzgur** [comment]
@rylev  Thanks for the report. It will be fixed wit the version  0.5.3
