### ISSUE TITLE
[Feature Request] Keyboard shortcut to view crate versions list "dialog box".

### ISSUE THREAD

**Issue by shanmukhateja** [serayuzgur/crates#97]
**Is your feature request related to a problem? Please describe.**
It would be wonderful if the crate's version info "dialog box" could be displayed with a keyboard shortcut like "Ctrl + Space" (or user defined). The current solution we have in place is to hover over crate's empty version field and get a list of suggestions. I am asking for possibility to extend the "dialog box" to listen to specific keyboard shortcut (like Ctrl + Space) as well.

**Describe the solution you'd like**
A trivial solution would be to listen to `keydown` event and check for shortcut combo. Whenever the user desired shortcut is pressed inside Cargo.toml "tab" on Editor, the version info dialog box would be visible. 

**Describe alternatives you've considered**
An alternative to the current visible dialog box would be to use VS Code's native 'dropdown' widget (the autocomplete widget which is visible with known types like enums). Hope this made sense!

**Additional context**
I am primarily a keyboard user and I prefer not to use the trackpad in general. I believe this feature would help devs like me who prefer keyboard shortcuts than mouse cursor. It would also improve accessibility for the extension as well.

**Comment by serayuzgur** [comment]
Hi @shanmukhateja  thanks for the issue. I relaized that it can be triggered with a shortcut according to your mappings.
Please take a look at [here](https://code.visualstudio.com/docs/getstarted/keybindings#_rich-languages-editing)

"Show Hover" is what you are looking for. Place your cursor (not mouse 😄  ) in to the dependency information and use the shortcut.

![hover](https://user-images.githubusercontent.com/4561330/90429382-4a245000-e0ce-11ea-8a12-1b7dfc389637.png)
