### ISSUE TITLE
Unable to manage extensions with large repos

### ISSUE THREAD

**Issue by dcormier** [serayuzgur/crates#99]
Crates with large repos seem to be problematic for the extension.

**To Reproduce**
1. Add this to your `Cargo.toml`:
```toml
[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]
```
2. Notice the red exclamation point that appears next to the version with an error message:
```text
web-sys: StatusCodeError: 403 - "{"message":"This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size.","errors":[{"resource":"Blob","field":"data","code":"too_large"}],"documentation_url":"https://docs.github.com/rest/reference/repos#get-repository-content\"}"
```

**Expected behavior**
The extension would be able to manage this dependency.

**Screenshots**
<img width="719" alt="image" src="https://user-images.githubusercontent.com/216265/90966643-cccc5700-e4a2-11ea-8ae2-f88da53f982e.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Version: vscode 1.48.1, crates extension version 0.5.2

**Comment by serayuzgur** [comment]
please use version 0.5.3 with localRepository enabled.

**Comment by dcormier** [comment]
I'm on 0.5.3 and I don't see a "localRepository" setting. Can you please elaborate?

**Comment by serayuzgur** [comment]
Please filter crates preferences it must be the last one
<img width="866" alt="image" src="https://user-images.githubusercontent.com/4561330/91763318-47e9e780-ebde-11ea-92cb-e4d92db908f9.png">

**Comment by dcormier** [comment]
OK. That does seem to work. Thank you.
